begin;

do $$
begin
  if exists(select 1 from public.warehouse_receipts where id in (
    '18550000-0000-4000-8000-000000000001'::uuid,
    '18550000-0000-4000-8000-000000000002'::uuid,
    '18550000-0000-4000-8000-000000000003'::uuid
  ) or receipt_number like 'UX5-WR-%-1855') then
    raise exception 'UX5_WR_FIXTURE_ALREADY_EXISTS';
  end if;
  if exists(select 1 from public.loads where id='18550000-0000-4000-8000-000000000021'::uuid) then
    raise exception 'UX5_WR_LOAD_FIXTURE_ALREADY_EXISTS';
  end if;
end;
$$;

insert into public.warehouse_receipts(id,receipt_number,warehouse_id,received_at,status,notes)
select v.id,v.receipt_number,w.id,now(),'received','UX5 WR reversible fixture'
from (values
  ('18550000-0000-4000-8000-000000000001'::uuid,'UX5-WR-HISTORY-1855'),
  ('18550000-0000-4000-8000-000000000002'::uuid,'UX5-WR-LOAD-1855'),
  ('18550000-0000-4000-8000-000000000003'::uuid,'UX5-WR-CLEAN-1855')
) as v(id,receipt_number)
cross join (select id from public.warehouses where active=true order by id limit 1) w;

insert into public.warehouse_receipt_items(id,receipt_id,product_id,pallets,quantity,unit,currency,notes)
select v.item_id,v.receipt_id,p.id,0,10,coalesce(nullif(btrim(p.unit),''),'unidades'),'USD','UX5 WR reversible fixture item'
from (values
  ('18550000-0000-4000-8000-000000000011'::uuid,'18550000-0000-4000-8000-000000000001'::uuid),
  ('18550000-0000-4000-8000-000000000012'::uuid,'18550000-0000-4000-8000-000000000002'::uuid),
  ('18550000-0000-4000-8000-000000000013'::uuid,'18550000-0000-4000-8000-000000000003'::uuid)
) as v(item_id,receipt_id)
cross join (select id,unit from public.products where active=true order by id limit 1) p;

-- Case 1: any movement history makes cancellation permanently unavailable.
insert into public.inventory_movements(id,warehouse_id,product_id,receipt_item_id,movement_type,quantity_delta,notes)
select '18550000-0000-4000-8000-000000000031'::uuid,wr.warehouse_id,wri.product_id,wri.id,'adjustment_in',1,'UX5 WR inventory-history fixture'
from public.warehouse_receipt_items wri
join public.warehouse_receipts wr on wr.id=wri.receipt_id
where wri.id='18550000-0000-4000-8000-000000000011'::uuid;

do $$
declare s jsonb;
begin
  s:=public.warehouse_receipt_action_state('18550000-0000-4000-8000-000000000001'::uuid);
  if coalesce((s#>>'{actions,cancel,allowed}')::boolean,false) is true then raise exception 'UX5_WR_HISTORY_CANCEL_FORBIDDEN'; end if;
  if s#>>'{actions,cancel,reason}' <> 'WR_HAS_INVENTORY_HISTORY' then raise exception 'UX5_WR_HISTORY_REASON_EXPECTED'; end if;
  begin
    perform public.assert_warehouse_receipt_action('18550000-0000-4000-8000-000000000001'::uuid,'cancel');
    raise exception 'UX5_WR_HISTORY_ASSERT_DID_NOT_BLOCK';
  exception when others then
    if position('WR_HAS_INVENTORY_HISTORY' in sqlerrm)=0 then raise; end if;
  end;
end;
$$;

-- Case 2: allocation to any non-cancelled Cargue blocks cancellation even with no movement history.
-- load_number remains generated by PostgreSQL; OVERRIDING keeps the identity sequence untouched.
insert into public.loads(id,load_serial,warehouse_id,status,notes) overriding system value
select '18550000-0000-4000-8000-000000000021'::uuid,18550001,warehouse_id,'draft','UX5 WR active-load fixture'
from public.warehouse_receipts where id='18550000-0000-4000-8000-000000000002'::uuid;

insert into public.load_items(id,load_id,product_id,planned_quantity,planned_pallets,unit,notes)
select '18550000-0000-4000-8000-000000000022'::uuid,'18550000-0000-4000-8000-000000000021'::uuid,product_id,1,0,unit,'UX5 WR active-load fixture item'
from public.warehouse_receipt_items where id='18550000-0000-4000-8000-000000000012'::uuid;

insert into public.load_allocations(id,load_item_id,receipt_item_id,allocated_quantity,allocated_pallets)
values ('18550000-0000-4000-8000-000000000023'::uuid,'18550000-0000-4000-8000-000000000022'::uuid,'18550000-0000-4000-8000-000000000012'::uuid,1,0);

do $$
declare s jsonb;
begin
  s:=public.warehouse_receipt_action_state('18550000-0000-4000-8000-000000000002'::uuid);
  if coalesce((s->>'has_inventory_history')::boolean,false) is true then raise exception 'UX5_WR_LOAD_CASE_SHOULD_HAVE_NO_HISTORY'; end if;
  if coalesce((s#>>'{actions,cancel,allowed}')::boolean,false) is true then raise exception 'UX5_WR_ACTIVE_LOAD_CANCEL_FORBIDDEN'; end if;
  if s#>>'{actions,cancel,reason}' <> 'WR_ASSIGNED_TO_LOAD' then raise exception 'UX5_WR_ACTIVE_LOAD_REASON_EXPECTED'; end if;
  begin
    perform public.assert_warehouse_receipt_action('18550000-0000-4000-8000-000000000002'::uuid,'cancel');
    raise exception 'UX5_WR_ACTIVE_LOAD_ASSERT_DID_NOT_BLOCK';
  exception when others then
    if position('WR_ASSIGNED_TO_LOAD' in sqlerrm)=0 then raise; end if;
  end;
end;
$$;

-- Case 3: a clean received WR is cancellable and becomes terminal afterwards.
do $$
declare s jsonb;
begin
  s:=public.warehouse_receipt_action_state('18550000-0000-4000-8000-000000000003'::uuid);
  if coalesce((s#>>'{actions,cancel,allowed}')::boolean,false) is not true then raise exception 'UX5_WR_CLEAN_CANCEL_EXPECTED'; end if;
  perform public.assert_warehouse_receipt_action('18550000-0000-4000-8000-000000000003'::uuid,'cancel');
end;
$$;

select public.cancel_warehouse_receipt_canonical('18550000-0000-4000-8000-000000000003'::uuid,null);

do $$
declare s jsonb;
begin
  s:=public.warehouse_receipt_action_state('18550000-0000-4000-8000-000000000003'::uuid);
  if s->>'receipt_status' <> 'cancelled' then raise exception 'UX5_WR_CANCEL_STATUS_EXPECTED'; end if;
  if coalesce((s#>>'{actions,cancel,allowed}')::boolean,false) is true then raise exception 'UX5_WR_REPEAT_CANCEL_FORBIDDEN'; end if;
  if s#>>'{actions,cancel,reason}' <> 'WR_NOT_RECEIVED' then raise exception 'UX5_WR_REPEAT_CANCEL_REASON_EXPECTED'; end if;
end;
$$;

rollback;

select
  (select count(*) from public.warehouse_receipts where id in ('18550000-0000-4000-8000-000000000001'::uuid,'18550000-0000-4000-8000-000000000002'::uuid,'18550000-0000-4000-8000-000000000003'::uuid) or receipt_number like 'UX5-WR-%-1855') as receipt_fixture_residue,
  (select count(*) from public.warehouse_receipt_items where id in ('18550000-0000-4000-8000-000000000011'::uuid,'18550000-0000-4000-8000-000000000012'::uuid,'18550000-0000-4000-8000-000000000013'::uuid)) as receipt_item_fixture_residue,
  (select count(*) from public.inventory_movements where id='18550000-0000-4000-8000-000000000031'::uuid) as movement_fixture_residue,
  (select count(*) from public.loads where id='18550000-0000-4000-8000-000000000021'::uuid) as load_fixture_residue,
  (select count(*) from public.load_items where id='18550000-0000-4000-8000-000000000022'::uuid) as load_item_fixture_residue,
  (select count(*) from public.load_allocations where id='18550000-0000-4000-8000-000000000023'::uuid) as allocation_fixture_residue;