(() => {
  if(window.__clientsModuleInstalled)return;
  window.__clientsModuleInstalled=true;
  const byId=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const fmtDate=value=>{if(!value)return 'No disponible';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('es-US');};
  const SAFE_CLIENT_ERRORS=new Set([
    'El nombre del cliente es obligatorio',
    'Ese cliente ya existe',
    'Cliente no encontrado',
    'El nombre es obligatorio',
    'Otro cliente ya utiliza ese WhatsApp o correo',
    'Número de WhatsApp inválido. Usa formato internacional, por ejemplo +5351234567.',
    'No tienes permiso para realizar esta acción',
    'No autorizado'
  ]);
  let importerState={importers:[],client_importers:[],shipment_importers:[]},menu=null,backdrop=null,activeClientId=null;

  function safeClientMessage(error,fallback){const message=String(error?.message||'').trim();return SAFE_CLIENT_ERRORS.has(message)?message:fallback;}
  function setClientMessage(message,ok=false){if(typeof window.note==='function')return window.note('clientMsg',message,ok);const node=byId('clientMsg');if(node){node.textContent=message||'';node.className=`msg ${message?(ok?'ok':'bad'):''}`;}}
  function setEditMessage(message,ok=false){const node=byId('clientEditMsg');if(node){node.textContent=message||'';node.className=`msg ${message?(ok?'ok':'bad'):''}`;}}

  function sectionHtml(){return `<div class="native-workspace-shell"><header class="native-workspace-hero"><div class="native-workspace-heading"><span class="native-workspace-kicker">Relaciones comerciales</span><h2>Clientes</h2><p>Centraliza contactos, empresas, importadoras y el historial de cada relación comercial.</p></div></header><div class="native-workspace-grid"><section class="card native-workspace-panel"><div class="native-workspace-panel-head"><h2>Agregar cliente</h2><p>Registra los datos esenciales; podrás completar el perfil y enviar la bienvenida después.</p></div><label>Nombre completo *</label><input id="clientName" placeholder="Nombre del cliente" autocomplete="name"><label>Empresa</label><input id="clientCompany" placeholder="Empresa o negocio" autocomplete="organization"><label>Nombre de la MIPYME</label><input id="clientMipyme" placeholder="Opcional"><label>Importadoras cubanas registradas</label><input id="clientImporters" placeholder="Ej. Cítricos Caribe, Quimimport"><div class="client-importer-help">Puedes registrar varias separadas por comas.</div><label>WhatsApp *</label><input id="clientPhone" placeholder="+5351234567" autocomplete="tel"><label>Correo</label><input id="clientEmail" type="email" autocomplete="email"><div class="native-workspace-form-actions"><button id="saveClient" class="orange" type="button">Guardar cliente</button></div><div id="clientMsg" class="msg" aria-live="polite"></div></section><section class="card native-workspace-panel"><div class="native-workspace-panel-head"><h2>Clientes registrados</h2><p>Consulta cada ficha y abre sus acciones desde un solo lugar.</p></div><div id="clients"></div></section></div></div>`;}
  async function loadImporters(){try{const result=await api('/api/importers');importerState={importers:result.importers||[],client_importers:result.client_importers||[],shipment_importers:result.shipment_importers||[]};window.importerState=importerState;}catch(error){console.error('CLIENT_IMPORTERS_LOAD_FAILED',error);}}
  function importerNames(clientId){const ids=new Set(importerState.client_importers.filter(link=>String(link.client_id)===String(clientId)).map(link=>String(link.importer_id)));return importerState.importers.filter(item=>ids.has(String(item.id))).map(item=>item.name);}
  function parseImporterNames(value){const map=new Map();String(value||'').split(',').forEach(raw=>{const clean=raw.trim().replace(/\s+/g,' ');if(clean)map.set(clean.toUpperCase(),clean);});return [...map.values()];}
  async function syncImporters(clientId,names){const result=await api('/api/importers',{method:'POST',body:JSON.stringify({action:'sync_client',client_id:clientId,importer_names:names})});if(result.state){importerState=result.state;window.importerState=importerState;}else await loadImporters();window.dispatchEvent(new CustomEvent('export-mca:importers-changed'));}
  function findClient(id){return Array.isArray(window.clients)?window.clients.find(item=>String(item.id)===String(id)):null;}
  function payload(prefix='client'){return {name:byId(prefix+'Name')?.value||'',company:byId(prefix+'Company')?.value||'',mipyme_name:byId(prefix+'Mipyme')?.value||'',phone:byId(prefix+'Phone')?.value||'',email:byId(prefix+'Email')?.value||''};}

  function render(){const target=byId('clients');if(!target)return;closeMenu();const rows=Array.isArray(window.clients)?window.clients:[];if(!rows.length){target.innerHTML='<div class="empty-state">No hay clientes registrados.</div><div class="client-list-footer">0 clientes</div>';return;}target.innerHTML=`<table><thead><tr><th>Nombre</th><th>Empresa</th><th>WhatsApp</th><th>Bienvenida</th><th>Acciones</th></tr></thead><tbody>${rows.map(client=>`<tr data-client-id="${esc(client.id)}"><td><b>${esc(client.name)}</b></td><td>${esc(client.company||'-')}</td><td>${esc(client.phone||'-')}</td><td><span class="pill ${client.welcome_status==='sent'?'done':''}">${esc(client.welcome_status||'pending')}</span></td><td class="client-actions-cell"><button class="client-actions-trigger" type="button" data-client-menu aria-label="Acciones de ${esc(client.name||'cliente')}">⋮</button></td></tr>`).join('')}</tbody></table><div class="client-list-footer">${rows.length} cliente${rows.length===1?'':'s'}</div>`;}
  function infoRow(label,value){return `<div class="client-information-row"><div class="client-information-label">${esc(label)}</div><div class="client-information-value">${esc(value||'No disponible')}</div></div>`;}
  function openInformation(id){const client=findClient(id);if(!client){setClientMessage('El cliente ya no está disponible.',false);return false;}const importers=importerNames(id);if(typeof window.openModal!=='function'){setClientMessage('No se pudo abrir la información del cliente.',false);return false;}window.openModal(`Información · ${client.name||'Cliente'}`,`<div class="client-information-grid"><section>${infoRow('Nombre completo',client.name)}${infoRow('Empresa',client.company)}${infoRow('MIPYME',client.mipyme_name)}<div class="client-information-row"><div class="client-information-label">Importadoras</div><div class="client-information-value">${importers.length?`<div class="client-importer-list">${importers.map(name=>`<div class="client-importer-item">${esc(name)}</div>`).join('')}</div><div class="muted" style="margin-top:7px">${importers.length} registro${importers.length===1?'':'s'}</div>`:'Sin registrar'}</div></div></section><section>${infoRow('WhatsApp',client.phone)}${infoRow('Correo',client.email)}${infoRow('Bienvenida',client.welcome_status||'pending')}${infoRow('Cliente creado',fmtDate(client.created_at))}${infoRow('Última actualización',fmtDate(client.updated_at))}</section></div>`);return true;}
  function editorHtml(client){return `<div class="grid"><div><label>Nombre completo *</label><input id="clientEditName" value="${esc(client.name||'')}"></div><div><label>Empresa</label><input id="clientEditCompany" value="${esc(client.company||'')}"></div><div><label>MIPYME</label><input id="clientEditMipyme" value="${esc(client.mipyme_name||'')}"></div><div><label>Importadoras</label><input id="clientEditImporters" value="${esc(importerNames(client.id).join(', '))}"></div><div><label>WhatsApp *</label><input id="clientEditPhone" value="${esc(client.phone||'')}"></div><div><label>Correo</label><input id="clientEditEmail" value="${esc(client.email||'')}"></div></div><div class="toolbar" style="justify-content:flex-end;margin-top:18px"><button id="cancelClientEdit" class="alt">Cancelar</button><button id="saveClientEdit" class="orange">Guardar cambios</button></div><div id="clientEditMsg" class="msg" aria-live="polite"></div>`;}
  function openEditor(id){const client=findClient(id);if(!client){setClientMessage('El cliente ya no está disponible.',false);return;}if(typeof window.openModal!=='function'){setClientMessage('No se pudo abrir el editor del cliente.',false);return;}window.openModal(`Editar cliente · ${client.name}`,editorHtml(client));byId('cancelClientEdit').onclick=()=>window.closeModal?.();byId('saveClientEdit').onclick=async()=>{const button=byId('saveClientEdit');button.disabled=true;setEditMessage('Guardando cambios...',true);try{await api('/api/clients',{method:'PATCH',body:JSON.stringify({id:client.id,...payload('clientEdit')})});await syncImporters(client.id,parseImporterNames(byId('clientEditImporters').value));window.closeModal?.();await loadAll();await loadImporters();render();setClientMessage('Cliente actualizado.',true);window.dispatchEvent(new CustomEvent('export-mca:clients-changed'));}catch(error){console.error('CLIENT_UPDATE_FAILED',error);setEditMessage(safeClientMessage(error,'No se pudo actualizar el cliente. Intenta nuevamente.'),false);button.disabled=false;}};}
  async function save(){const button=byId('saveClient');if(!button||button.disabled)return;button.disabled=true;const original=button.textContent;button.textContent='Guardando...';let createdId=null;setClientMessage('Guardando cliente...',true);try{const result=await api('/api/clients',{method:'POST',body:JSON.stringify(payload('client'))});createdId=result.client?.id||null;if(createdId)await syncImporters(createdId,parseImporterNames(byId('clientImporters').value));setClientMessage('Cliente guardado. La bienvenida se envía desde Acciones.',true);['clientName','clientCompany','clientMipyme','clientImporters','clientPhone','clientEmail'].forEach(id=>{if(byId(id))byId(id).value='';});await loadAll();await loadImporters();render();window.dispatchEvent(new CustomEvent('export-mca:clients-changed'));}catch(error){console.error('CLIENT_CREATE_FAILED',error);if(createdId){try{await api('/api/clients?id='+encodeURIComponent(createdId),{method:'DELETE'});}catch(rollbackError){console.error('CLIENT_CREATE_ROLLBACK_FAILED',rollbackError);}}setClientMessage(safeClientMessage(error,'No se pudo guardar el cliente. Revisa los datos e intenta nuevamente.'),false);}finally{button.disabled=false;button.textContent=original;}}

  function clientDecision(title,message,confirmLabel='Confirmar'){return new Promise(resolve=>{document.querySelector('.client-decision-overlay')?.remove();const overlay=document.createElement('div');overlay.className='client-decision-overlay';overlay.innerHTML=`<div class="client-decision-panel" role="dialog" aria-modal="true" aria-labelledby="clientDecisionTitle"><h3 id="clientDecisionTitle">${esc(title)}</h3><p>${esc(message)}</p><div class="client-decision-actions"><button type="button" class="alt" data-client-decision-cancel>Cancelar</button><button type="button" class="danger" data-client-decision-confirm>${esc(confirmLabel)}</button></div></div>`;document.body.appendChild(overlay);const finish=value=>{overlay.remove();resolve(value);};overlay.querySelector('[data-client-decision-cancel]').onclick=()=>finish(false);overlay.querySelector('[data-client-decision-confirm]').onclick=()=>finish(true);overlay.onclick=event=>{if(event.target===overlay)finish(false);};});}

  async function sendWelcome(id){const client=findClient(id);if(!client){setClientMessage('El cliente ya no está disponible.',false);return;}setClientMessage('Enviando bienvenida...',true);try{const result=await api('/api/clients',{method:'PATCH',body:JSON.stringify({id,action:'resend_welcome'})});const status=String(result?.welcome?.status||'pending');if(status==='sent')setClientMessage('Bienvenida enviada correctamente.',true);else if(status==='pending_config')setClientMessage('La bienvenida quedó pendiente porque la plantilla de envío no está disponible.',false);else if(status==='failed')setClientMessage('No se pudo enviar la bienvenida. Revisa el Centro de alertas y comunicaciones.',false);else setClientMessage('La bienvenida quedó pendiente de envío.',false);await loadAll();if(typeof window.loadNotifications==='function')await window.loadNotifications();}catch(error){console.error('CLIENT_WELCOME_FAILED',error);setClientMessage(safeClientMessage(error,'No se pudo procesar la bienvenida. Intenta nuevamente.'),false);}}

  async function openHistory(id,title){try{const result=await api('/api/history?client_id='+encodeURIComponent(id));const events=[...(result.events||[]),...(result.notifications||[]),...(result.audit_events||[])].sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));const html=events.length?`<div class="timeline">${events.map(event=>`<div class="event"><b>${esc(event.title||event.action||event.event_type||'Evento')}</b><div>${esc(event.details||event.status||event.delivery_status||'')}</div><div class="muted">${esc(fmtDate(event.created_at))}</div></div>`).join('')}</div>`:'<div class="empty-state">No hay actividad registrada para este cliente.</div>';if(typeof window.openModal==='function')window.openModal(`Cliente · ${title||'Historial'}`,html);else setClientMessage('No se pudo abrir el historial del cliente.',false);}catch(error){console.error('CLIENT_HISTORY_FAILED',error);setClientMessage('No se pudo cargar el historial del cliente. Intenta nuevamente.',false);}}

  async function deleteClient(id,name){const approved=await clientDecision('Eliminar cliente',`Se eliminará ${name||'este cliente'}. Esta acción solo debe usarse cuando el registro ya no deba permanecer en el ERP.`,'Eliminar');if(!approved)return;setClientMessage('Eliminando cliente...',true);try{await api('/api/clients?id='+encodeURIComponent(id),{method:'DELETE'});await loadAll();await loadImporters();render();setClientMessage('Cliente eliminado.',true);window.dispatchEvent(new CustomEvent('export-mca:clients-changed'));}catch(error){console.error('CLIENT_DELETE_FAILED',error);setClientMessage(safeClientMessage(error,'No se pudo eliminar el cliente. Puede tener operaciones relacionadas.'),false);}}

  function ensureMenu(){if(!backdrop){backdrop=document.createElement('div');backdrop.className='client-actions-backdrop';document.body.appendChild(backdrop);backdrop.onclick=closeMenu;}if(!menu){menu=document.createElement('div');menu.className='client-actions-popover hidden';document.body.appendChild(menu);menu.onclick=event=>{const button=event.target.closest('[data-client-action]');if(!button)return;const id=activeClientId,action=button.dataset.clientAction;const client=findClient(id);closeMenu();if(!client)return setClientMessage('El cliente ya no está disponible.',false);if(action==='information')openInformation(id);else if(action==='edit')openEditor(id);else if(action==='welcome')sendWelcome(id);else if(action==='history')openHistory(id,client.name);else if(action==='delete')deleteClient(id,client.name);};}document.addEventListener('click',event=>{if(!menu.classList.contains('hidden')&&!menu.contains(event.target)&&!event.target.closest('[data-client-menu]'))closeMenu();});}
  function closeMenu(){menu?.classList.add('hidden');backdrop?.classList.remove('show');document.body.classList.remove('client-actions-open');activeClientId=null;}
  function openMenu(client,trigger){ensureMenu();activeClientId=client.id;menu.innerHTML=`<button data-client-action="information">Información</button><button data-client-action="edit">Editar</button><button data-client-action="welcome">${client.welcome_status==='sent'?'Reenviar bienvenida':'Enviar bienvenida'}</button><button data-client-action="history">Historial</button><button class="danger" data-client-action="delete">Eliminar</button>`;menu.classList.remove('hidden');if(matchMedia('(max-width:700px)').matches){backdrop.classList.add('show');document.body.classList.add('client-actions-open');return;}const rect=trigger.getBoundingClientRect(),width=230;menu.style.left=`${Math.max(8,Math.min(rect.right-width,innerWidth-width-8))}px`;menu.style.top=`${Math.min(rect.bottom+7,innerHeight-menu.offsetHeight-8)}px`;}

  async function mount(){const section=byId('clientsSection');if(!section)return;section.innerHTML=sectionHtml();ensureMenu();await loadImporters();byId('saveClient').onclick=save;byId('clients').onclick=event=>{const trigger=event.target.closest('[data-client-menu]');if(!trigger)return;const client=findClient(trigger.closest('[data-client-id]')?.dataset.clientId);if(client)openMenu(client,trigger);};window.renderClients=render;window.editClient=openEditor;window.ClientsModule=Object.freeze({render,openInformation,openEditor,sendWelcome,openHistory,deleteClient,owner:'clients-module.js'});render();window.addEventListener('export-mca:data-loaded',render);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
