(() => {
  if(window.__clientsModuleInstalled)return;
  window.__clientsModuleInstalled=true;
  const byId=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const fmtDate=value=>{if(!value)return 'No disponible';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('es-US');};
  let importerState={importers:[],client_importers:[],shipment_importers:[]},menu=null,backdrop=null,activeClientId=null;

  function installStyles(){if(byId('clientsModuleStyles'))return;const style=document.createElement('style');style.id='clientsModuleStyles';style.textContent=`
    .client-actions-cell{width:1%;white-space:nowrap;text-align:right}.client-actions-trigger{width:38px!important;height:38px!important;min-width:38px!important;padding:0!important;border:1px solid #cfd7e3!important;border-radius:10px!important;background:#fff!important;color:#06204a!important;font-size:24px!important;display:inline-grid!important;place-items:center!important}.client-actions-popover{position:fixed;z-index:1800;min-width:230px;background:#fff;border:1px solid #dfe5ee;border-radius:12px;padding:7px;box-shadow:0 18px 45px rgba(6,32,74,.22)}.client-actions-popover.hidden{display:none!important}.client-actions-popover button{width:100%!important;display:flex!important;background:#fff!important;color:#152238!important;border:0!important;padding:11px 12px!important;text-align:left!important}.client-actions-popover button:hover{background:#f4f7fb!important}.client-actions-popover button.danger{color:#b42318!important;border-top:1px solid #e6ebf2!important;margin-top:5px!important}.client-actions-backdrop{display:none;position:fixed;inset:0;z-index:1799;background:rgba(6,20,42,.35)}.client-actions-backdrop.show{display:block}.client-information-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 22px}.client-information-row{padding:12px 0;border-bottom:1px solid #e6ebf2}.client-information-label{font-size:11px;font-weight:800;text-transform:uppercase;color:#667085;margin-bottom:5px}.client-information-value{font-size:15px;color:#152238;word-break:break-word}.client-importer-help{font-size:11px;color:var(--muted);margin-top:5px;line-height:1.45}.client-importer-list{display:grid;gap:7px}.client-importer-item{padding:8px 10px;border:1px solid #e1e7ef;border-radius:9px;background:#f8fafc}.client-list-footer{text-align:right;margin-top:12px;color:#667085;font-size:12px;font-weight:800}@media(max-width:700px){.client-information-grid{grid-template-columns:1fr}.client-actions-popover{left:12px!important;right:12px!important;bottom:12px!important;top:auto!important;width:auto!important}.client-actions-backdrop.show{display:block}body.client-actions-open{overflow:hidden!important}.client-list-footer{text-align:left}}
  `;document.head.appendChild(style);}

  function sectionHtml(){return `<div class="grid"><section class="card"><h2>Agregar cliente</h2><label>Nombre completo *</label><input id="clientName" placeholder="Nombre del cliente" autocomplete="name"><label>Empresa</label><input id="clientCompany" placeholder="Empresa o negocio" autocomplete="organization"><label>Nombre de la MIPYME</label><input id="clientMipyme" placeholder="Opcional"><label>Importadoras cubanas registradas</label><input id="clientImporters" placeholder="Ej. Cítricos Caribe, Quimimport"><div class="client-importer-help">Puedes registrar varias separadas por comas.</div><label>WhatsApp *</label><input id="clientPhone" placeholder="+5351234567" autocomplete="tel"><label>Correo</label><input id="clientEmail" type="email" autocomplete="email"><div style="margin-top:14px"><button id="saveClient" class="orange" type="button">Guardar cliente</button></div><div id="clientMsg" class="msg"></div></section><section class="card"><h2>Clientes registrados</h2><div id="clients"></div></section></div>`;}
  async function loadImporters(){try{const result=await api('/api/importers');importerState={importers:result.importers||[],client_importers:result.client_importers||[],shipment_importers:result.shipment_importers||[]};window.importerState=importerState;}catch(error){console.error('[clients importers]',error);}}
  function importerNames(clientId){const ids=new Set(importerState.client_importers.filter(link=>String(link.client_id)===String(clientId)).map(link=>String(link.importer_id)));return importerState.importers.filter(item=>ids.has(String(item.id))).map(item=>item.name);}
  function parseImporterNames(value){const map=new Map();String(value||'').split(',').forEach(raw=>{const clean=raw.trim().replace(/\s+/g,' ');if(clean)map.set(clean.toUpperCase(),clean);});return [...map.values()];}
  async function syncImporters(clientId,names){const result=await api('/api/importers',{method:'POST',body:JSON.stringify({action:'sync_client',client_id:clientId,importer_names:names})});if(result.state){importerState=result.state;window.importerState=importerState;}else await loadImporters();window.dispatchEvent(new CustomEvent('export-mca:importers-changed'));}
  function findClient(id){return Array.isArray(window.clients)?window.clients.find(item=>String(item.id)===String(id)):null;}
  function payload(prefix='client'){return {name:byId(prefix+'Name')?.value||'',company:byId(prefix+'Company')?.value||'',mipyme_name:byId(prefix+'Mipyme')?.value||'',phone:byId(prefix+'Phone')?.value||'',email:byId(prefix+'Email')?.value||''};}

  function render(){const target=byId('clients');if(!target)return;closeMenu();const rows=Array.isArray(window.clients)?window.clients:[];if(!rows.length){target.innerHTML='<div class="empty-state">No hay clientes registrados.</div><div class="client-list-footer">0 clientes</div>';return;}target.innerHTML=`<table><thead><tr><th>Nombre</th><th>Empresa</th><th>WhatsApp</th><th>Bienvenida</th><th>Acciones</th></tr></thead><tbody>${rows.map(client=>`<tr data-client-id="${esc(client.id)}"><td><b>${esc(client.name)}</b></td><td>${esc(client.company||'-')}</td><td>${esc(client.phone||'-')}</td><td><span class="pill ${client.welcome_status==='sent'?'done':''}">${esc(client.welcome_status||'pending')}</span></td><td class="client-actions-cell"><button class="client-actions-trigger" type="button" data-client-menu aria-label="Acciones">⋮</button></td></tr>`).join('')}</tbody></table><div class="client-list-footer">${rows.length} cliente${rows.length===1?'':'s'}</div>`;}
  function infoRow(label,value){return `<div class="client-information-row"><div class="client-information-label">${esc(label)}</div><div class="client-information-value">${esc(value||'No disponible')}</div></div>`;}
  function openInformation(id){const client=findClient(id);if(!client)return alert('Cliente no encontrado.');const importers=importerNames(id);openModal(`Información · ${client.name||'Cliente'}`,`<div class="client-information-grid"><section>${infoRow('Nombre completo',client.name)}${infoRow('Empresa',client.company)}${infoRow('MIPYME',client.mipyme_name)}<div class="client-information-row"><div class="client-information-label">Importadoras</div><div class="client-information-value">${importers.length?`<div class="client-importer-list">${importers.map(name=>`<div class="client-importer-item">${esc(name)}</div>`).join('')}</div><div class="muted" style="margin-top:7px">${importers.length} registro${importers.length===1?'':'s'}</div>`:'Sin registrar'}</div></div></section><section>${infoRow('WhatsApp',client.phone)}${infoRow('Correo',client.email)}${infoRow('Bienvenida',client.welcome_status||'pending')}${infoRow('Cliente creado',fmtDate(client.created_at))}${infoRow('Última actualización',fmtDate(client.updated_at))}</section></div>`);}
  function editorHtml(client){return `<div class="grid"><div><label>Nombre completo *</label><input id="clientEditName" value="${esc(client.name||'')}"></div><div><label>Empresa</label><input id="clientEditCompany" value="${esc(client.company||'')}"></div><div><label>MIPYME</label><input id="clientEditMipyme" value="${esc(client.mipyme_name||'')}"></div><div><label>Importadoras</label><input id="clientEditImporters" value="${esc(importerNames(client.id).join(', '))}"></div><div><label>WhatsApp *</label><input id="clientEditPhone" value="${esc(client.phone||'')}"></div><div><label>Correo</label><input id="clientEditEmail" value="${esc(client.email||'')}"></div></div><div class="toolbar" style="justify-content:flex-end;margin-top:18px"><button id="cancelClientEdit" class="alt">Cancelar</button><button id="saveClientEdit" class="orange">Guardar cambios</button></div><div id="clientEditMsg" class="msg"></div>`;}
  function openEditor(id){const client=findClient(id);if(!client)return;openModal(`Editar cliente · ${client.name}`,editorHtml(client));byId('cancelClientEdit').onclick=closeModal;byId('saveClientEdit').onclick=async()=>{const button=byId('saveClientEdit');button.disabled=true;try{await api('/api/clients',{method:'PATCH',body:JSON.stringify({id:client.id,...payload('clientEdit')})});await syncImporters(client.id,parseImporterNames(byId('clientEditImporters').value));closeModal();await loadAll();await loadImporters();render();window.dispatchEvent(new CustomEvent('export-mca:clients-changed'));}catch(error){byId('clientEditMsg').textContent=error.message;button.disabled=false;}};}
  async function save(){const button=byId('saveClient');if(!button||button.disabled)return;button.disabled=true;const original=button.textContent;button.textContent='Guardando...';let createdId=null;try{const result=await api('/api/clients',{method:'POST',body:JSON.stringify(payload('client'))});createdId=result.client?.id||null;if(createdId)await syncImporters(createdId,parseImporterNames(byId('clientImporters').value));note('clientMsg',result.welcome?.status==='sent'?'Cliente guardado y bienvenida enviada.':'Cliente guardado.',true);['clientName','clientCompany','clientMipyme','clientImporters','clientPhone','clientEmail'].forEach(id=>{if(byId(id))byId(id).value='';});await loadAll();await loadImporters();render();window.dispatchEvent(new CustomEvent('export-mca:clients-changed'));}catch(error){if(createdId){try{await api('/api/clients?id='+encodeURIComponent(createdId),{method:'DELETE'});}catch{}}note('clientMsg',error.message);}finally{button.disabled=false;button.textContent=original;}}

  function ensureMenu(){installStyles();if(!backdrop){backdrop=document.createElement('div');backdrop.className='client-actions-backdrop';document.body.appendChild(backdrop);backdrop.onclick=closeMenu;}if(!menu){menu=document.createElement('div');menu.className='client-actions-popover hidden';document.body.appendChild(menu);menu.onclick=event=>{const button=event.target.closest('[data-client-action]');if(!button)return;const id=activeClientId,action=button.dataset.clientAction;closeMenu();if(action==='information')openInformation(id);else if(action==='edit')openEditor(id);else if(action==='welcome')welcome(id);else if(action==='history'){const c=findClient(id);if(c)clientHistory(id,c.name);}else if(action==='delete'){const c=findClient(id);if(c)delClient(id,c.name);}};}document.addEventListener('click',event=>{if(!menu.classList.contains('hidden')&&!menu.contains(event.target)&&!event.target.closest('[data-client-menu]'))closeMenu();});}
  function closeMenu(){menu?.classList.add('hidden');backdrop?.classList.remove('show');document.body.classList.remove('client-actions-open');activeClientId=null;}
  function openMenu(client,trigger){ensureMenu();activeClientId=client.id;menu.innerHTML=`<button data-client-action="information">Información</button><button data-client-action="edit">Editar</button><button data-client-action="welcome">${client.welcome_status==='sent'?'Reenviar bienvenida':'Enviar bienvenida'}</button><button data-client-action="history">Historial</button><button class="danger" data-client-action="delete">Eliminar</button>`;menu.classList.remove('hidden');if(matchMedia('(max-width:700px)').matches){backdrop.classList.add('show');document.body.classList.add('client-actions-open');return;}const rect=trigger.getBoundingClientRect(),width=230;menu.style.left=`${Math.max(8,Math.min(rect.right-width,innerWidth-width-8))}px`;menu.style.top=`${Math.min(rect.bottom+7,innerHeight-menu.offsetHeight-8)}px`;}

  async function mount(){const section=byId('clientsSection');if(!section)return;section.innerHTML=sectionHtml();ensureMenu();await loadImporters();byId('saveClient').onclick=save;byId('clients').onclick=event=>{const trigger=event.target.closest('[data-client-menu]');if(!trigger)return;const client=findClient(trigger.closest('[data-client-id]')?.dataset.clientId);if(client)openMenu(client,trigger);};window.renderClients=render;window.editClient=openEditor;window.ClientsModule=Object.freeze({render,openInformation,openEditor,owner:'clients-module.js'});render();window.addEventListener('export-mca:data-loaded',render);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();