const token=localStorage.getItem('export_mca_token');if(!token){location.href='/admin/';}
let state={loads:[],warehouses:[],sources:[],clients:[],importers:[],shipments:[],stats:{},write_access:false,selected:null,editing:null};
let decisionResolver=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Error');return d;}
const fmt=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:3});
const date=v=>v?new Date(v).toLocaleString('es-US',{dateStyle:'short',timeStyle:'short'}):'—';
const labels={draft:'Borrador',reserved:'Reservado',loading:'En carga',loaded:'Cargado',dispatched:'Despachado',cancelled:'Cancelado'};
const unitLabel=u=>{const v=String(u||'unidades').trim();return /^\d+([.,]\d+)?$/.test(v)?'unidades':v;};
const capability=(load,key)=>load?.capabilities?.actions?.[key]||null;
const can=(load,key)=>capability(load,key)?.allowed===true;
function quantityText(q,u,p){const parts=[];if(Number(q)>0)parts.push(`${fmt(q)} ${esc(unitLabel(u))}`);if(Number(p)>0)parts.push(`${fmt(p)} ${Number(p)===1?'pallet':'pallets'}`);return parts.length?parts.join(' · '):'0';}
function movementText(q,u,label){return Number(q)>0?`<span class="active">${label}: ${fmt(q)} ${esc(unitLabel(u))}</span>`:`<span class="muted">${label}: 0</span>`;}
function metric(label,value){return `<div class="metric"><b>${value||0}</b><span>${label}</span></div>`;}
function renderMetrics(){const s=state.stats;$('metrics').innerHTML=metric('Total',s.total)+metric('Borrador',s.draft)+metric('Reservados',s.reserved)+metric('En carga',s.loading)+metric('Cargados',s.loaded)+metric('Despachados',s.dispatched);}
function filteredLoads(){const q=$('search').value.trim().toLowerCase(),f=$('statusFilter').value;return state.loads.filter(l=>(!f||l.status===f)&&(!q||[l.load_number,l.warehouse?.name,l.warehouse?.code,l.shipment?.container_number].some(x=>String(x||'').toLowerCase().includes(q))));}
function renderRows(){const rows=filteredLoads();$('loadRows').innerHTML=rows.map(l=>`<tr data-id="${l.id}"><td><strong>${esc(l.load_number)}</strong></td><td><span class="pill ${l.status}">${labels[l.status]||l.status}</span></td><td>${esc(l.warehouse?.code||l.warehouse?.name||'—')}</td><td>${esc(l.shipment?.container_number||'Pendiente de asignar')}</td><td>${date(l.scheduled_at)}</td><td>${date(l.updated_at)}</td></tr>`).join('');$('empty').classList.toggle('hidden',rows.length>0);document.querySelectorAll('#loadRows tr').forEach(tr=>tr.onclick=()=>openLoad(tr.dataset.id));}
async function refresh(){const d=await api('/api/loads?bootstrap=1');Object.assign(state,d);$('newLoad').hidden=state.write_access!==true;renderMetrics();renderRows();fillSelects();}
function fillSelects(){const wh=state.warehouses.map(x=>`<option value="${x.id}">${esc(x.code||x.name)} · ${esc(x.name)}</option>`).join('');$('planWarehouse').innerHTML='<option value="">Seleccionar...</option>'+wh;$('containerClient').innerHTML='<option value="">Sin asignar</option>'+state.clients.map(x=>`<option value="${x.id}">${esc(x.company||x.name)}</option>`).join('');$('containerImporter').innerHTML='<option value="">Sin asignar</option>'+state.importers.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('existingContainer').innerHTML='<option value="">Seleccionar...</option>'+state.shipments.map(x=>`<option value="${x.id}">${esc(x.container_number)} · ${esc(x.operational_status||'Activo')}</option>`).join('');}
function flow(status){const all=['draft','reserved','loading','loaded','dispatched'];const idx=all.indexOf(status);return `<div class="status-flow">${all.map((x,i)=>`<span class="status-step ${i<idx?'done':i===idx?'current':''}">${labels[x]}</span>`).join('')}</div>`;}
function wrLink(receiptNumber){const wr=String(receiptNumber||'').trim();return wr?`<button class="context-link" type="button" data-open-wr="${esc(wr)}">Ver WR en Inventario</button>`:'';}
function actionButtons(l){
  const actions=[];
  if(can(l,'assign_container')||can(l,'create_container'))actions.push(['container','Asignar contenedor','']);
  if(can(l,'unassign_container'))actions.push(['unassign_container','Quitar contenedor','']);
  if(can(l,'reserve'))actions.push(['reserve','Reservar','primary']);
  if(can(l,'release'))actions.push(['release','Liberar reserva','']);
  if(can(l,'start_loading'))actions.push(['start_loading','Iniciar carga','primary']);
  if(can(l,'mark_loaded'))actions.push(['mark_loaded','Marcar cargado','primary']);
  if(can(l,'dispatch'))actions.push(['dispatch','Despachar','orange']);
  if(can(l,'edit'))actions.push(['edit','Editar plan','']);
  if(can(l,'cancel'))actions.push(['cancel','Cancelar','danger']);
  if(can(l,'view_tracking'))actions.push(['tracking','Ver Tracking','']);
  return actions;
}
function renderLoadDetail(l){
  const t=l.traceability||[];
  const itemHtml=(l.items||[]).map(i=>`<div class="product-group"><div class="product-head"><div><strong>${esc(i.product?.name||i.product_id)}</strong><span class="quantity-sub">Total del producto en este cargue</span></div><div class="qty">${quantityText(i.planned_quantity,i.unit,i.planned_pallets)}</div></div><div class="product-body">${(i.allocations||[]).map(a=>{const wr=a.receipt_item?.receipt?.receipt_number||'WR';return `<div class="allocation-row"><div><strong>${esc(wr)}</strong>${a.receipt_item?.lot_number?`<span class="quantity-sub">Lote ${esc(a.receipt_item.lot_number)}</span>`:''}${wrLink(wr)}</div><div class="allocation-value"><b>Asignado: ${quantityText(a.allocated_quantity,i.unit,a.allocated_pallets)}</b><small>Origen de esta mercancía</small></div></div>`;}).join('')}</div></div>`).join('');
  const trace=t.length?`<div class="trace-table"><div class="trace-head"><span>Origen (WR)</span><span>Producto</span><span>Cantidad asignada</span><span>Movimientos</span></div>${t.map(x=>`<div class="trace-row"><span><strong>${esc(x.receipt_number)}</strong><br>${wrLink(x.receipt_number)}</span><span>${esc(x.product_name)}</span><span>${quantityText(x.allocated_quantity,x.product_unit||'unidades',x.allocated_pallets)}</span><span class="movement">${movementText(x.reserved_quantity_net,x.product_unit||'unidades','Reservado')}${movementText(x.dispatched_quantity,x.product_unit||'unidades','Despachado')}</span></div>`).join('')}</div>`:'<div class="muted">Sin trazabilidad todavía.</div>';
  const actions=actionButtons(l);
  const pending=l.capabilities?.container_pending===true?'<div class="pending-note">Contenedor pendiente de asignar. El backend habilitará el despacho solamente cuando exista un contenedor elegible.</div>':'';
  return `<div class="section"><div class="section-title">Estado operativo<span class="pill ${l.status}">${labels[l.status]||l.status}</span></div><div class="section-body">${flow(l.status)}<div class="actions" style="margin-top:12px">${actions.map(a=>`<button class="btn ${a[2]}" data-action="${a[0]}">${a[1]}</button>`).join('')}</div>${pending}<div id="actionMsg" class="muted" style="margin-top:8px"></div></div></div><div class="section"><div class="section-title">Resumen</div><div class="section-body"><div class="kv"><div><small>Almacén</small><strong>${esc(l.warehouse?.name||'—')}</strong></div><div><small>Contenedor</small><strong>${esc(l.shipment?.container_number||'Pendiente de asignar')}</strong></div><div><small>Programado</small><strong>${date(l.scheduled_at)}</strong></div><div><small>Booking</small><strong>${esc(l.shipment?.booking_number||'—')}</strong></div><div><small>B/L</small><strong>${esc(l.shipment?.bol_number||'—')}</strong></div><div><small>Seguimiento</small><strong>ERP</strong></div></div></div></div><div class="section"><div class="section-title">Mercancía <span>${(l.items||[]).length} línea(s)</span></div><div class="section-body">${itemHtml||'<div class="muted">Sin mercancía.</div>'}</div></div><div class="section"><div class="section-title">Trazabilidad por WR</div><div class="section-body">${trace}</div></div>`;
}
async function openLoad(id){const d=await api('/api/loads?id='+encodeURIComponent(id));state.selected=d.load;$('drawerTitle').textContent=d.load.load_number;$('drawerSub').textContent=(labels[d.load.status]||d.load.status)+' · '+(d.load.warehouse?.name||'');$('drawerBody').innerHTML=renderLoadDetail(d.load);$('drawerModal').classList.remove('hidden');document.querySelectorAll('#drawerBody [data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action));document.querySelectorAll('#drawerBody [data-open-wr]').forEach(b=>b.onclick=e=>{e.stopPropagation();try{parent.OperationalNavigation?.openInventoryReceipt?.(b.dataset.openWr);}catch{}});}
function showActionMessage(message){const el=$('actionMsg');if(el)el.textContent=message||'';}
function requestDecision(action){
  const copy=action==='dispatch'?{title:'Confirmar despacho',text:'Esta acción confirma la salida física del almacén y afecta el ledger de inventario.',button:'Despachar'}:{title:'Cancelar cargue',text:'Esta acción cancela el cargue. Si existe una reserva activa, el backend la liberará de forma transaccional.',button:'Cancelar cargue'};
  $('decisionTitle').textContent=copy.title;$('decisionText').textContent=copy.text;$('decisionAccept').textContent=copy.button;$('decisionModal').classList.remove('hidden');
  return new Promise(resolve=>{decisionResolver=resolve;});
}
function closeDecision(accepted){$('decisionModal').classList.add('hidden');const resolve=decisionResolver;decisionResolver=null;if(resolve)resolve(accepted===true);}
async function handleAction(action){
  const l=state.selected;if(!l)return;
  if(action==='tracking'){if(!can(l,'view_tracking'))return;try{parent.OperationalNavigation?.openTracking?.({shipmentId:l.shipment_id,containerNumber:l.shipment?.container_number});}catch{}return;}
  if(action==='container'){if(!(can(l,'assign_container')||can(l,'create_container')))return;openContainer(l);return;}
  if(action==='edit'){if(!can(l,'edit'))return;openPlan(l);return;}
  if(!can(l,action))return;
  if(['dispatch','cancel'].includes(action)){const accepted=await requestDecision(action);if(!accepted)return;}
  try{bsy(true);showActionMessage('');await api('/api/loads',{method:'POST',body:JSON.stringify({action,load_id:l.id})});$('drawerModal').classList.add('hidden');await refresh();await openLoad(l.id);}catch(e){showActionMessage(e.message);}finally{bsy(false);}
}
function bsy(on){document.querySelectorAll('button').forEach(b=>b.disabled=on);}
function openPlan(load=null){if(load&&!can(load,'edit'))return;if(!load&&state.write_access!==true)return;state.editing=load;$('planTitle').textContent=load?`Editar ${load.load_number}`:'Nuevo cargue';$('planWarehouse').disabled=Boolean(load);$('planWarehouse').value=load?.warehouse_id||'';$('planScheduled').value=load?.scheduled_at?new Date(new Date(load.scheduled_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';$('planNotes').value=load?.notes||'';$('planMsg').textContent='';renderSources(load);$('planModal').classList.remove('hidden');}
function renderSources(load){const wh=$('planWarehouse').value;const sources=state.sources.filter(s=>!wh||s.warehouse_id===wh);const existing=new Map();(load?.items||[]).forEach(i=>(i.allocations||[]).forEach(a=>existing.set(a.receipt_item_id,{q:a.allocated_quantity,p:a.allocated_pallets})));const groups={};sources.forEach(s=>(groups[s.product_id]??=[]).push(s));$('sourceGroups').innerHTML=Object.values(groups).map(g=>`<div class="product-group"><div class="product-head"><strong>${esc(g[0].product_name)}</strong><span class="muted">${esc(unitLabel(g[0].product_unit||g[0].receipt_unit||'unidades'))}</span></div><div class="product-body">${g.map(s=>{const e=existing.get(s.receipt_item_id)||{};return `<div class="source" data-source="${s.receipt_item_id}" data-product="${s.product_id}" data-unit="${esc(unitLabel(s.product_unit||s.receipt_unit||'unidades'))}"><div class="source-top"><span><strong>${esc(s.receipt_number)}</strong>${s.lot_number?` · Lote ${esc(s.lot_number)}`:''}</span><small>Disponible: ${quantityText(s.available_quantity,s.product_unit||s.receipt_unit,s.available_pallets)}</small></div><div class="alloc-grid"><input type="number" step="0.001" min="0" max="${s.available_quantity}" data-q value="${e.q||''}" placeholder="Cantidad"><input type="number" step="0.001" min="0" max="${s.available_pallets}" data-p value="${e.p||''}" placeholder="Pallets"></div></div>`;}).join('')}</div></div>`).join('')||'<div class="empty">Selecciona un almacén con inventario disponible.</div>';}
function planPayload(){const byProduct={};document.querySelectorAll('#sourceGroups [data-source]').forEach(row=>{const q=Number(row.querySelector('[data-q]').value||0),p=Number(row.querySelector('[data-p]').value||0);if(q<=0&&p<=0)return;const pid=row.dataset.product;(byProduct[pid]??={product_id:pid,unit:row.dataset.unit,planned_quantity:0,planned_pallets:0,allocations:[]});byProduct[pid].planned_quantity+=q;byProduct[pid].planned_pallets+=p;byProduct[pid].allocations.push({receipt_item_id:row.dataset.source,allocated_quantity:q,allocated_pallets:p});});return Object.values(byProduct);}
async function savePlan(){if(state.editing&&!can(state.editing,'edit'))return $('planMsg').textContent='El cargue ya no admite edición.';if(!state.editing&&state.write_access!==true)return $('planMsg').textContent='No tienes permiso para crear cargues.';const lines=planPayload();if(!$('planWarehouse').value)return $('planMsg').textContent='Selecciona un almacén.';if(!lines.length)return $('planMsg').textContent='Selecciona al menos una cantidad de un WR.';try{bsy(true);const body={action:state.editing?'replace_plan':'create_plan',load_id:state.editing?.id,warehouse_id:$('planWarehouse').value,scheduled_at:$('planScheduled').value?new Date($('planScheduled').value).toISOString():null,notes:$('planNotes').value,lines};const d=await api('/api/loads',{method:'POST',body:JSON.stringify(body)});$('planModal').classList.add('hidden');await refresh();await openLoad(d.load.id);}catch(e){$('planMsg').textContent=e.message;}finally{bsy(false);}}
function openContainer(l){if(!(can(l,'assign_container')||can(l,'create_container')))return;$('containerLoadLabel').textContent=l.load_number;$('containerNumber').value='';$('containerCarrier').value='';$('containerBooking').value='';$('containerBol').value='';$('containerMsg').textContent='';$('createContainer').hidden=!can(l,'create_container');$('assignExisting').hidden=!can(l,'assign_container');$('containerModal').classList.remove('hidden');}
async function createContainer(){if(!can(state.selected,'create_container'))return;try{bsy(true);await api('/api/loads',{method:'POST',body:JSON.stringify({action:'create_container',load_id:state.selected.id,container_number:$('containerNumber').value,carrier:$('containerCarrier').value,booking_number:$('containerBooking').value,bol_number:$('containerBol').value,client_id:$('containerClient').value||null,importer_id:$('containerImporter').value||null})});$('containerModal').classList.add('hidden');$('drawerModal').classList.add('hidden');await refresh();await openLoad(state.selected.id);}catch(e){$('containerMsg').textContent=e.message;}finally{bsy(false);}}
async function assignExisting(){if(!can(state.selected,'assign_container'))return;if(!$('existingContainer').value)return;try{bsy(true);await api('/api/loads',{method:'POST',body:JSON.stringify({action:'assign_existing_container',load_id:state.selected.id,shipment_id:$('existingContainer').value})});$('containerModal').classList.add('hidden');$('drawerModal').classList.add('hidden');await refresh();await openLoad(state.selected.id);}catch(e){$('containerMsg').textContent=e.message;}finally{bsy(false);}}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));
$('newLoad').onclick=()=>openPlan();$('refresh').onclick=refresh;$('search').oninput=renderRows;$('statusFilter').onchange=renderRows;$('planWarehouse').onchange=()=>renderSources(state.editing);$('savePlan').onclick=savePlan;$('createContainer').onclick=createContainer;$('assignExisting').onclick=assignExisting;$('decisionAccept').onclick=()=>closeDecision(true);$('decisionReject').onclick=()=>closeDecision(false);
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target!==m)return;if(m.id==='decisionModal')closeDecision(false);else m.classList.add('hidden');}));
refresh().catch(e=>{$('empty').classList.remove('hidden');$('empty').textContent=e.message;});
