const token=localStorage.getItem('export_mca_token');
if(!token) location.href='/admin/';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number(v||0);
const fmt=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:3}).format(n(v));
const money=(v,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:2}).format(n(v));
const pad=v=>String(v).padStart(2,'0');
let orders=[],clients=[],importers=[],clientImporters=[],products=[],view='open',editing=null,detailOrder=null,lineSeq=0;

async function api(path,opt={}){
  const r=await fetch(path,{...opt,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opt.headers||{})}});
  const d=await r.json().catch(()=>({}));
  if(r.status===401){localStorage.removeItem('export_mca_token');location.href='/admin/';throw new Error('Sesión vencida')}
  if(!r.ok)throw new Error(d.error||'Error');return d;
}
function localDateToday(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function localToIso(v){if(!v)return null;const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error('Fecha y hora inválida');return d.toISOString()}
function toLocalInput(v){if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return '';return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function date(v){if(!v)return '—';const m=String(v).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[2]}/${m[3]}/${m[1]}`:new Date(v).toLocaleDateString('es-US')}
function dateTime(v){return v?new Date(v).toLocaleString('es-US'):'—'}
function statusLabel(s){return({draft:'Borrador',confirmed:'Confirmada',closed:'Cerrada',cancelled:'Cancelada'})[s]||s}
function statusClass(s){return s==='confirmed'?'ok':s==='cancelled'?'bad':s==='closed'?'off':''}
function fulfillmentLabel(s){return({pending:'Pendiente',partial:'Parcial',planned:'Planificado',prepared:'Preparado',dispatched:'Despachado'})[s]||s||'Pendiente'}
function fulfillmentClass(s){return s==='dispatched'?'ok':['partial','prepared','planned'].includes(s)?'warn':''}
function clientName(c){return c?.company||c?.mipyme_name||c?.name||'—'}
function orderTotal(o){return n(o.progress?.order_total||(o.items||[]).reduce((s,i)=>s+n(i.ordered_quantity)*n(i.unit_price),0))}

async function load(){const d=await api('/api/sales');orders=d.orders||[];clients=d.clients||[];importers=d.importers||[];clientImporters=d.client_importers||[];products=d.products||[];fillMasters();render()}
function fillMasters(){
  $('oClient').innerHTML='<option value="">Seleccionar cliente</option>'+clients.map(c=>`<option value="${c.id}">${esc(clientName(c))}</option>`).join('');
  syncImporters();
}
function syncImporters(selected=''){
  const cid=$('oClient').value;
  const allowed=new Set(clientImporters.filter(x=>x.client_id===cid).map(x=>x.importer_id));
  $('oImporter').innerHTML='<option value="">Sin importador definido</option>'+importers.filter(i=>allowed.has(i.id)).map(i=>`<option value="${i.id}" ${i.id===selected?'selected':''}>${esc(i.name)}</option>`).join('');
}
function filtered(){const q=$('search').value.trim().toLowerCase();return orders.filter(o=>{const ok=view==='all'||(view==='draft'?o.status==='draft':view==='closed'?['closed','cancelled'].includes(o.status):o.status==='confirmed');const hay=[o.so_number,clientName(o.client),o.importer?.name,o.customer_reference,...(o.items||[]).flatMap(i=>[i.product?.sku,i.product?.name,i.product?.brand])].join(' ').toLowerCase();return ok&&(!q||hay.includes(q))})}
function render(){
  const confirmed=orders.filter(o=>o.status==='confirmed').length,draft=orders.filter(o=>o.status==='draft').length,partial=orders.filter(o=>o.progress?.fulfillment_status==='partial').length,dispatched=orders.filter(o=>o.progress?.fulfillment_status==='dispatched').length;
  $('metrics').innerHTML=`<div class="metric"><span>Total SO</span><b>${orders.length}</b></div><div class="metric"><span>Borradores</span><b>${draft}</b></div><div class="metric"><span>Confirmadas</span><b>${confirmed}</b></div><div class="metric"><span>En proceso</span><b>${partial}</b></div><div class="metric"><span>Despachadas</span><b>${dispatched}</b></div>`;
  const list=filtered();
  $('orderList').innerHTML=list.length?list.map(o=>`<article class="row"><div><div class="po">${esc(o.so_number)}</div><div class="small">${date(o.order_date)}</div></div><div><b>${esc(clientName(o.client))}</b><div class="small">${esc(o.importer?.name||'Sin importador')}</div></div><div><b>${money(orderTotal(o),o.currency)}</b><div class="small">${(o.items||[]).length} línea(s)</div></div><div><span class="pill ${statusClass(o.status)}">${statusLabel(o.status)}</span></div><div><span class="pill ${fulfillmentClass(o.progress?.fulfillment_status)}">${fulfillmentLabel(o.progress?.fulfillment_status)}</span><div class="small">${o.progress?.fully_dispatched_items||0}/${o.progress?.item_count||0} completas</div></div><div>${esc(o.customer_reference||'—')}<div class="small">${dateTime(o.requested_at)}</div></div><div class="actions"><button class="btn" data-view-order="${o.id}">Ver</button>${o.status==='draft'?`<button class="btn" data-edit-order="${o.id}">Editar</button>`:''}</div></article>`).join(''):'<div class="empty">No hay Sales Orders en esta vista.</div>';
  document.querySelectorAll('[data-view-order]').forEach(b=>b.onclick=()=>openDetail(b.dataset.viewOrder));
  document.querySelectorAll('[data-edit-order]').forEach(b=>b.onclick=()=>openOrder(orders.find(o=>o.id===b.dataset.editOrder)));
}
function productOptions(selected=''){return '<option value="">Seleccionar producto</option>'+products.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.sku?p.sku+' · ':'')}${esc(p.name)}</option>`).join('')}
function addLine(seed={}){
  lineSeq++;const div=document.createElement('div');div.className='line';
  div.innerHTML=`<div class="line-head"><div class="line-title">Línea ${$('orderLines').children.length+1}</div><button class="btn danger" type="button">Quitar</button></div><div class="grid3"><div><label>Producto *</label><select class="lProduct">${productOptions(seed.product_id||'')}</select></div><div><label>Cantidad vendida *</label><input class="lQty" type="number" min="0" step="0.001" value="${esc(seed.ordered_quantity||'')}"></div><div><label>Pallets</label><input class="lPallets" type="number" min="0" step="0.001" value="${esc(seed.ordered_pallets||'')}"></div></div><div class="grid3"><div><label>Unidades por pallet</label><input class="lUpp" type="number" min="0" step="0.001" value="${esc(seed.units_per_pallet||'')}"></div><div><label>Precio unitario *</label><input class="lPrice" type="number" min="0" step="0.0001" value="${esc(seed.unit_price??'')}"></div><div><label>Notas</label><input class="lNotes" value="${esc(seed.notes||'')}"></div></div><div class="small lProductInfo"></div>`;
  $('orderLines').appendChild(div);div.querySelector('button').onclick=()=>{div.remove();if(!$('orderLines').children.length)addLine()};div.querySelector('.lProduct').onchange=()=>syncProduct(div);syncProduct(div)
}
function syncProduct(div){const p=products.find(x=>x.id===div.querySelector('.lProduct').value);div.querySelector('.lProductInfo').textContent=p?[p.brand,p.unit,p.package_format].filter(Boolean).join(' · '):'';if(p&&!div.querySelector('.lUpp').value&&p.default_units_per_pallet)div.querySelector('.lUpp').value=p.default_units_per_pallet}
function collectLines(){return [...document.querySelectorAll('#orderLines .line')].map(div=>({product_id:div.querySelector('.lProduct').value,ordered_quantity:div.querySelector('.lQty').value,ordered_pallets:div.querySelector('.lPallets').value,units_per_pallet:div.querySelector('.lUpp').value,unit_price:div.querySelector('.lPrice').value,notes:div.querySelector('.lNotes').value}))}
function openOrder(order=null){editing=order||null;$('orderTitle').textContent=order?`Editar ${order.so_number}`:'Nueva Sales Order';$('oClient').value=order?.client_id||'';syncImporters(order?.importer_id||'');$('oCurrency').value=order?.currency||'USD';$('oDate').value=order?.order_date||localDateToday();$('oRequested').value=toLocalInput(order?.requested_at);$('oReference').value=order?.customer_reference||'';$('oNotes').value=order?.notes||'';$('orderLines').innerHTML='';(order?.items?.length?order.items:[{}]).forEach(addLine);$('orderMsg').textContent='';$('orderModal').classList.remove('hidden')}
function closeModal(name){$(name+'Modal').classList.add('hidden');if(name==='order')editing=null;if(name==='detail')detailOrder=null}
async function saveOrder(){const btn=$('saveOrder');try{btn.disabled=true;$('orderMsg').textContent='';const body={action:editing?'replace_plan':'create_plan',sales_order_id:editing?.id,client_id:$('oClient').value,importer_id:$('oImporter').value,order_date:$('oDate').value,requested_at:localToIso($('oRequested').value),currency:$('oCurrency').value,customer_reference:$('oReference').value,notes:$('oNotes').value,lines:collectLines()};await api('/api/sales',{method:'POST',body:JSON.stringify(body)});closeModal('order');await load()}catch(e){$('orderMsg').textContent=e.message}finally{btn.disabled=false}}
function progressText(p,item){if(!p)return 'Sin planificación física';return `Planificado: ${fmt(p.planned_quantity)} · Preparado: ${fmt(p.prepared_quantity)} · Despachado: ${fmt(p.dispatched_quantity)} · Pendiente de despacho: ${fmt(p.remaining_to_dispatch_quantity)} ${esc(item.unit)}`}
function openDetail(id){
  detailOrder=orders.find(o=>o.id===id);if(!detailOrder)return;const o=detailOrder;$('detailTitle').textContent=o.so_number;$('detailSubtitle').textContent=`${clientName(o.client)} · ${statusLabel(o.status)} · ${fulfillmentLabel(o.progress?.fulfillment_status)}`;
  $('detailBody').innerHTML=`<div class="summary"><div><b>Cliente</b>${esc(clientName(o.client))}</div><div><b>Importador</b>${esc(o.importer?.name||'—')}</div><div><b>Fecha / objetivo</b>${date(o.order_date)}<br><span class="small">${dateTime(o.requested_at)}</span></div><div><b>Total venta</b>${money(orderTotal(o),o.currency)}</div></div><div class="summary"><div><b>Estado comercial</b><span class="pill ${statusClass(o.status)}">${statusLabel(o.status)}</span></div><div><b>Cumplimiento</b><span class="pill ${fulfillmentClass(o.progress?.fulfillment_status)}">${fulfillmentLabel(o.progress?.fulfillment_status)}</span></div><div><b>Referencia cliente</b>${esc(o.customer_reference||'—')}</div><div><b>Notas</b>${esc(o.notes||'—')}</div></div><div class="detail-items">${(o.items||[]).map(i=>`<div class="detail-item"><div class="line-head"><div><b>${esc(i.product?.sku?i.product.sku+' · ':'')}${esc(i.product?.name||'Producto')}</b><div class="small">${esc(i.product?.brand||'')} ${esc(i.product?.package_format||'')}</div></div><span class="pill ${fulfillmentClass(i.progress?.fulfillment_stage)}">${fulfillmentLabel(i.progress?.fulfillment_stage)}</span></div><div class="progress">Vendido: <b>${fmt(i.ordered_quantity)} ${esc(i.unit)}</b>${n(i.ordered_pallets)?` · ${fmt(i.ordered_pallets)} pallets`:''} · Precio: <b>${money(i.unit_price,o.currency)}</b></div><div class="small">${progressText(i.progress,i)}</div>${(i.allocations||[]).length?`<div class="small">Cargues: ${(i.allocations||[]).map(a=>`${esc(a.load_item?.load?.load_number||'—')} · ${esc(fulfillmentLabel(a.load_item?.load?.status))} · ${fmt(a.allocated_quantity)} ${esc(i.unit)}`).join(' | ')}</div>`:''}</div>`).join('')}</div>`;
  const acts=[];if(o.status==='draft')acts.push(`<button class="btn" data-action="edit">Editar</button><button class="btn primary" data-action="confirm">Confirmar SO</button><button class="btn danger" data-action="cancel">Cancelar</button>`);if(o.status==='confirmed'){if(o.progress?.fulfillment_status==='dispatched')acts.push(`<button class="btn primary" data-action="close">Cerrar SO</button>`);acts.push(`<button class="btn danger" data-action="cancel">Cancelar</button>`)}$('detailActions').innerHTML=acts.join('');$('detailActions').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>detailAction(b.dataset.action));$('detailMsg').textContent='';$('detailModal').classList.remove('hidden')
}
async function detailAction(action){if(!detailOrder)return;if(action==='edit'){const o=detailOrder;closeModal('detail');openOrder(o);return}if(!confirm(action==='confirm'?'¿Confirmar esta Sales Order? Después sus líneas quedan bloqueadas.':action==='cancel'?'¿Cancelar esta Sales Order?':'¿Cerrar esta Sales Order?'))return;try{$('detailMsg').textContent='';await api('/api/sales',{method:'POST',body:JSON.stringify({action,sales_order_id:detailOrder.id})});closeModal('detail');await load()}catch(e){$('detailMsg').textContent=e.message}}

$('newOrder').onclick=()=>openOrder();$('refresh').onclick=load;$('addOrderLine').onclick=()=>addLine();$('saveOrder').onclick=saveOrder;$('oClient').onchange=()=>syncImporters();$('search').oninput=render;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id.replace('Modal',''))}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal:not(.hidden)').forEach(m=>closeModal(m.id.replace('Modal','')))});
load().catch(e=>$('orderList').innerHTML=`<div class="empty">${esc(e.message)}</div>`);
