import {test,expect} from '@playwright/test';
import {publicationsWorkflowFixture,fixturePhoto} from '../../scripts/lib/figma-publications-workflow-fixture.mjs';
async function open(page,module,options={}){
 const url='https://erp-visual.invalid/?embedded=1',html=publicationsWorkflowFixture({module,...options});
 await page.route(/^https?:\/\//,route=>{const requested=route.request().url();if(requested===url)return route.fulfill({contentType:'text/html',body:html});if(/^https:\/\/erp-visual\.invalid\/storage\/v1\/object\/public\/publication-images\/photo-\d+\.png$/.test(requested))return route.fulfill({contentType:'image/png',body:Buffer.from(fixturePhoto,'base64')});return route.abort();});
 page.on('console',message=>{if(message.type()==='error')console.log('Fixture browser diagnostic:',message.text().slice(0,400));});await page.goto(url);await page.evaluate(()=>document.fonts.ready);
 if(module==='publications'){if(!options.failRead)await expect(page.locator('#totalMetric')).toHaveText('4');await expect(page.locator('#totalMetric')).toHaveCSS('font-size','32px');await expect(page.locator('.publications-hero')).toHaveCSS('padding','0px');}
 else if(options.writable!==false){await page.locator(module==='routes'?'[data-workflow-routes-open]':'[data-task-supervisor-open]').click();if(!options.failRead)await expect(page.locator(module==='routes'?'#workflowRoutesModal':'#taskSupervisorModal')).toHaveAttribute('aria-busy','false');}
}
const writes=page=>page.evaluate(()=>window.__fixtureCalls.filter(c=>c.method!=='GET'));
async function shot(page,info,name,fullPage=false){const path=info.outputPath(name+'.png');await page.screenshot({path,fullPage,animations:'disabled',scale:'css'});await info.attach(name,{path,contentType:'image/png'});}
async function fits(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize().width);}
async function hit(page,selector){const node=page.locator(selector);await node.scrollIntoViewIfNeeded();expect(await node.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===el;})).toBe(true);}
async function contrast(page,selector){await page.locator(selector).hover();expect(await page.locator(selector).evaluate(el=>{const s=getComputedStyle(el),l=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),a=l(s.color),b=l(s.backgroundColor);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);})).toBeGreaterThanOrEqual(4.5);}
const rowForm=page=>page.locator('[data-workflow-route-form="shipment_cuba_documents"]');
for(const width of [1440,390]){
 test(`Publications: catalog, search, statuses and editor focus at ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:1000});await open(page,'publications');await fits(page);await expect(page.locator('#activeList tbody tr')).toHaveCount(3);await expect(page.locator('#hiddenList .pill')).toBeVisible();await expect(page.locator('#hiddenList .pill')).toHaveText('Oculto');await shot(page,info,'publicaciones',true);
  await page.locator('#publicationsSearch').fill('Ana Pérez');await expect(page.locator('#activeList tbody tr')).toHaveCount(1);await expect(page.locator('#hiddenList tbody tr')).toHaveCount(1);await expect(page.locator('#totalMetric')).toHaveText('4');await page.locator('#publicationsSearch').fill('ninguna coincidencia');await expect(page.locator('#activeList .empty')).toBeVisible();await page.locator('#publicationsSearch').fill('');
  const trigger=page.locator('[data-action="edit"][data-id="publication-0"]');await trigger.click();await expect(page.locator('#title')).toBeFocused();await expect(page.locator('#title')).toHaveValue('Mercancía disponible');await page.keyboard.press('Escape');await expect(page.locator('#publicationEditorModal')).toBeHidden();await expect(trigger).toBeFocused();expect(await writes(page)).toEqual([]);
 });
}
for(const viewport of [{width:1440,height:700},{width:390,height:500}]){
 test(`Publication creation preserves a failed draft and validates upcoming dates at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'publications');await page.locator('#newBtn').click();await expect(page.locator('#title')).toBeFocused();await page.locator('#saveBtn').click();await expect(page.locator('#msg')).toHaveText('El título es obligatorio');expect(await writes(page)).toEqual([]);
  await page.locator('#title').fill('Próxima salida de ejemplo');await page.locator('#category').selectOption('upcoming_shipments');await page.locator('#saveBtn').click();await expect(page.locator('#msg')).toContainText('al menos una fecha');expect(await writes(page)).toEqual([]);
  await page.locator('#departure_date').fill('2026-09-30');await page.locator('#price').fill('1250');await page.locator('#quantity').fill('20');await page.locator('#unit').fill('Cajas');await page.locator('#assigned_worker_id').selectOption('worker-0');await page.locator('#description').fill('Descripción comercial de ejemplo.');await page.locator('#location_public').fill('Miami, FL');await page.locator('#location_internal').fill('Referencia privada de prueba');await page.locator('#availability_status').selectOption('upcoming');
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await page.locator('#saveBtn').click();await expect(page.locator('#msg')).toContainText('No se pudo guardar');await expect(page.locator('#title')).toHaveValue('Próxima salida de ejemplo');await page.locator('#cancelBtn').click();await expect(page.locator('#newBtn')).toBeFocused();await page.locator('#newBtn').click();await expect(page.locator('#title')).toHaveValue('Próxima salida de ejemplo');await expect(page.locator('[data-form-draft-copy]')).toContainText('Borrador recuperado');await hit(page,'#saveBtn');await contrast(page,'#saveBtn');await fits(page);await shot(page,info,'nueva-publicacion');
  await page.evaluate(()=>{window.__fixtureRejectWrites=false;window.__fixtureWriteDelay=100;document.querySelector('#publicationForm').requestSubmit();document.querySelector('#publicationForm').requestSubmit();});await expect(page.locator('#publicationEditorModal')).toBeHidden();await expect(page.locator('#totalMetric')).toHaveText('5');const sent=await writes(page);expect(sent).toHaveLength(2);expect(sent[1].body).toMatchObject({category:'upcoming_shipments',title:'Próxima salida de ejemplo',price:'1250',quantity:'20',unit:'Cajas',currency:'USD',assigned_worker_id:'worker-0',departure_date:'2026-09-30',arrival_date:'',image_urls:[],publication_status:'draft',location_internal:'Referencia privada de prueba'});
 });
 test(`Publication photos rollback failed removal and keep the two-photo limit at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'publications');await page.locator('[data-action="edit"][data-id="publication-0"]').click();await expect(page.locator('.photo')).toHaveCount(2);await page.locator('#title').fill('Mercancía actualizada');await page.evaluate(()=>window.__fixtureRejectWrites=true);await page.locator('[data-remove-photo="0"]').click();await expect(page.locator('#photoStatus')).toContainText('No se pudo quitar');await expect(page.locator('.photo')).toHaveCount(2);await expect(page.locator('#title')).toHaveValue('Mercancía actualizada');
  await page.evaluate(()=>window.__fixtureRejectWrites=false);await page.locator('[data-remove-photo="0"]').click();await expect(page.locator('#photoStatus')).toContainText('1 de 2');await page.locator('#photoInput').setInputFiles({name:'example.png',mimeType:'image/png',buffer:Buffer.from(fixturePhoto,'base64')});await expect(page.locator('#photoStatus')).toContainText('2 de 2');await expect(page.locator('.photo')).toHaveCount(2);
  const before=await writes(page);await page.locator('#photoInput').setInputFiles({name:'extra.png',mimeType:'image/png',buffer:Buffer.from(fixturePhoto,'base64')});await expect(page.locator('#photoStatus')).toContainText('máximo de 2');expect(await writes(page)).toHaveLength(before.length);await fits(page);await shot(page,info,'editar-publicacion-fotos');await page.locator('#saveBtn').click();await expect(page.locator('#publicationEditorModal')).toBeHidden();const sent=await writes(page);expect(sent.filter(c=>c.path==='/api/publication-images'&&c.method==='POST')).toHaveLength(1);expect(sent.at(-1)).toMatchObject({method:'PATCH',body:{id:'publication-0',title:'Mercancía actualizada'}});expect(sent.at(-1).body.image_urls).toHaveLength(2);
 });
 test(`Publication status and deletion require a deliberate decision at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'publications');await page.locator('[data-action="status"][data-id="publication-0"]').click();await expect(page.locator('#hiddenList tbody tr')).toHaveCount(2);await page.locator('#hiddenList [data-action="status"][data-id="publication-0"]').click();await expect(page.locator('#publishedMetric')).toHaveText('1');
  const trigger=page.locator('[data-action="delete"][data-id="publication-0"]');await trigger.click();await expect(page.locator('#publicationDecisionCancel')).toBeFocused();await page.locator('#publicationDecisionClose').focus();await page.keyboard.press('Shift+Tab');await expect(page.locator('#publicationDecisionConfirm')).toBeFocused();await hit(page,'#publicationDecisionConfirm');await fits(page);await shot(page,info,'eliminar-publicacion');await page.keyboard.press('Escape');await expect(trigger).toBeFocused();expect((await writes(page)).filter(c=>c.method==='DELETE')).toHaveLength(0);
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await trigger.click();await page.locator('#publicationDecisionConfirm').click();await expect(page.locator('#pageMessage')).toContainText('No se pudo completar');await expect(page.locator('#totalMetric')).toHaveText('4');await page.evaluate(()=>window.__fixtureRejectWrites=false);await trigger.click();await page.locator('#publicationDecisionConfirm').click();await expect(page.locator('#totalMetric')).toHaveText('3');expect((await writes(page)).at(-1)).toMatchObject({path:'/api/publications',method:'DELETE',query:'?id=publication-0'});
 });
 test(`Automatic assignments preserve other route drafts and enforce team membership at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'routes');const form=rowForm(page),other=page.locator('[data-workflow-route-form="purchase_receipt"]');await expect(page.locator('[data-workflow-routes-close]')).toBeFocused();await expect(form.locator('[data-route-assignee] option')).toHaveCount(3);await other.locator('[name="default_priority"]').selectOption('critical');await form.locator('[data-route-team]').selectOption('team-1');await expect(form.locator('[data-route-assignee]')).toHaveValue('');await expect(form.locator('[data-route-assignee] option')).toHaveCount(2);await form.locator('[data-route-assignee]').selectOption('operator-1');await form.locator('[name="default_due_hours"]').fill('0');await form.locator('button[type=submit]').click();expect(await writes(page)).toEqual([]);
  await form.locator('[name="default_due_hours"]').fill('72');await form.locator('[name="default_priority"]').selectOption('high');await page.evaluate(()=>window.__fixtureRejectWrites=true);await form.locator('button[type=submit]').click();await expect(page.locator('#workflowRoutesMessage')).toContainText('No se pudo guardar');await expect(form.locator('[data-route-assignee]')).toHaveValue('operator-1');await expect(other.locator('[name="default_priority"]')).toHaveValue('critical');await contrast(page,'[data-workflow-route-form="shipment_cuba_documents"] button[type=submit]');await fits(page);await shot(page,info,'asignaciones-automaticas');
  await page.evaluate(()=>{window.__fixtureRejectWrites=false;window.__fixtureWriteDelay=100;const f=document.querySelector('[data-workflow-route-form="shipment_cuba_documents"]');f.requestSubmit();f.requestSubmit();});await expect(page.locator('#workflowRoutesMessage')).toHaveText('Asignación automática actualizada.');await expect(other.locator('[name="default_priority"]')).toHaveValue('critical');await expect(form.locator('button[type=submit]')).toBeFocused();expect(await writes(page)).toHaveLength(2);expect((await writes(page)).at(-1).body).toEqual({workflow_key:'shipment_cuba_documents',enabled:true,default_priority:'high',default_due_hours:'72',assigned_team_id:'team-1',assigned_admin_id:'operator-1'});
  await page.locator('[data-workflow-reconcile]').click();await expect(page.locator('#workflowRoutesMessage')).toHaveText('Trabajo vigente sincronizado.');expect((await writes(page)).at(-1).body).toEqual({action:'reconcile_current'});await expect(other.locator('[name="default_priority"]')).toHaveValue('critical');await page.keyboard.press('Escape');await expect(page.locator('[data-workflow-routes-open]')).toBeFocused();
 });
 test(`Supervisor filters preserve keyboard access to the selected task at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'supervisor');await expect(page.locator('#taskSupervisorSummary button')).toHaveCount(6);await expect(page.locator('#taskSupervisorTable tbody tr')).toHaveCount(4);await expect(page.locator('.task-route-health-state')).toHaveText(['Compatible','Sin asignar']);await fits(page);await shot(page,info,'supervision');
  await page.locator('[data-task-supervisor-filter="routing"]').click();await expect(page.locator('[data-task-supervisor-filter="routing"]')).toBeFocused();await expect(page.locator('#taskSupervisorTable tbody tr')).toHaveCount(1);await expect(page.locator('#taskSupervisorTable')).toContainText('Coordinar entrega');await page.locator('[data-task-supervisor-filter="all"]').click();await page.locator('#taskSupervisorPriority').selectOption('critical');await expect(page.locator('#taskSupervisorTable tbody tr')).toHaveCount(1);await page.locator('#taskSupervisorPriority').selectOption('all');await page.locator('#taskSupervisorWorkflow').selectOption('shipment_cuba_documents');await page.locator('#taskSupervisorSearch').fill('documentación');await expect(page.locator('#taskSupervisorTable tbody tr')).toHaveCount(1);
  await page.locator('[data-supervisor-task="task-0"] button').focus();await page.keyboard.press('Enter');await expect(page.locator('#taskSupervisorModal')).toBeHidden();expect(await page.evaluate(()=>window.__fixtureOpenedTask)).toBe('task-0');expect(await writes(page)).toEqual([]);
 });
}
test('Read-only publications allow inspection without editing or uploads',async({page})=>{
 await open(page,'publications',{writable:false});await expect(page.locator('#newBtn')).toBeDisabled();await expect(page.locator('[data-action="status"],[data-action="delete"]')).toHaveCount(0);await page.locator('[data-action="edit"][data-id="publication-0"]').click();await expect(page.locator('#publicationEditorClose')).toBeFocused();await expect(page.locator('#readOnlyNote')).toBeVisible();for(const id of ['title','photoInput','saveBtn'])await expect(page.locator('#'+id)).toBeDisabled();await page.locator('#cancelBtn').click();await expect(page.locator('#publicationEditorModal')).toBeHidden();expect(await writes(page)).toEqual([]);
});
test('Workflow management remains inaccessible without tasks.manage',async({page})=>{
 await open(page,'routes',{writable:false});await expect(page.locator('[data-workflow-routes-open],[data-task-supervisor-open]')).toHaveCount(0);await page.evaluate(()=>window.TaskSupervisorQueue.open());await expect(page.locator('#taskSupervisorModal')).toHaveCount(0);expect(await page.evaluate(()=>window.__fixtureCalls)).toEqual([]);
});
test('Supervisor restores the queue if task navigation fails',async({page})=>{
 await open(page,'supervisor');await page.evaluate(()=>window.__fixtureMissingTask=true);await page.locator('[data-supervisor-task="task-0"] button').click();await expect(page.locator('#taskSupervisorMessage')).toHaveText('No se pudo abrir la tarea. Intenta nuevamente.');await expect(page.locator('[data-task-supervisor-close]')).toBeFocused();await expect(page.locator('body')).toHaveClass(/task-supervisor-open/);expect(await writes(page)).toEqual([]);
});
for(const module of ['publications','routes','supervisor'])test(`${module}: read failures retain a safe retry`,async({page})=>{
 await open(page,module,{failRead:true});const message=module==='publications'?'#pageMessage':module==='routes'?'#workflowRoutesMessage':'#taskSupervisorMessage';await expect(page.locator(message)).toContainText('No se pud');await expect(page.locator('body')).not.toContainText('PRIVATE_FIXTURE_ERROR');await page.evaluate(()=>window.__fixtureReadError=false);await page.locator(module==='publications'?'#refreshPublications':module==='routes'?'[data-workflow-routes-refresh]':'[data-task-supervisor-refresh]').click();if(module==='publications')await expect(page.locator('#totalMetric')).toHaveText('4');else if(module==='routes')await expect(page.locator('[data-workflow-route-form]')).toHaveCount(3);else await expect(page.locator('#taskSupervisorSummary button')).toHaveCount(6);expect(await writes(page)).toEqual([]);
});
