import {test,expect} from '@playwright/test';
import {accessAccountFixture} from '../../scripts/lib/figma-access-account-fixture.mjs';

async function open(page,module='access',options={}){
 const url='https://erp-visual.invalid/',html=accessAccountFixture({module,...options});
 await page.route('**/*',route=>route.request().url()===url?route.fulfill({contentType:'text/html',body:html}):route.abort());
 await page.goto(url);await page.evaluate(()=>document.fonts.ready);await expect.poll(()=>page.evaluate(()=>window.__fixtureReady||window.__fixtureError)).toBe(true);
}
const writes=page=>page.evaluate(()=>window.__fixtureCalls.filter(c=>c.method!=='GET'));
async function shot(page,info,name,fullPage=false){const path=info.outputPath(name+'.png');await page.screenshot({path,fullPage,animations:'disabled',scale:'css'});await info.attach(name,{path,contentType:'image/png'});}
async function fits(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize().width);}
async function hit(page,selector){const el=page.locator(selector);await el.scrollIntoViewIfNeeded();expect(await el.evaluate(n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===n;})).toBe(true);}
const tab=async(page,key)=>{await page.locator(`[data-access-tab="${key}"]`).click();await expect(page.locator('#accessCreateButton')).toBeEnabled();};
const modalSave=page=>page.locator('#accessModalFoot .access-primary');
const closeModal=async page=>{await page.keyboard.press('Escape');await expect(page.locator('#accessModal')).toBeHidden();};

for(const width of [1440,980,390])test(`Access directory: search, keyboard and account restrictions at ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:'dark'});await open(page);await fits(page);await expect(page.locator('.access-card')).toHaveCount(4);await shot(page,info,'usuarios',true);
 const master=page.locator('.access-card').filter({hasText:'Cuenta maestra de ejemplo'}),self=page.locator('.access-card').filter({hasText:'Ana Pérez'});
 await expect(master.locator('button')).toHaveCount(0);await expect(self.locator('[data-access-action="toggle-user"]')).toHaveCount(0);
 await page.locator('[data-access-view="all"]').focus();await page.keyboard.press('End');await expect(page.locator('[data-access-view="inactive"]')).toBeFocused();await expect(page.locator('.access-card')).toHaveCount(1);
 await page.keyboard.press('Home');await page.locator('#accessSearch').fill('logística');await expect(page.locator('.access-card')).toHaveCount(1);await expect(page.locator('.access-card')).toContainText('Luis García');
 await page.locator('[data-access-action="clear-search"]').click();await expect(page.locator('#accessSearch')).toBeFocused();await expect(page.locator('.access-card')).toHaveCount(4);
 await page.locator('[data-access-tab="users"]').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('[data-access-tab="roles"]')).toBeFocused();await expect(page.locator('#accessCreateButton')).toHaveText('Nuevo rol');await expect(page.locator('#accessCreateButton')).toBeEnabled();await fits(page);await shot(page,info,'roles',true);
 await page.keyboard.press('End');await expect(page.locator('[data-access-tab="teams"]')).toBeFocused();await expect(page.locator('#accessCreateButton')).toHaveText('Nuevo equipo');await expect(page.locator('#accessCreateButton')).toBeEnabled();await fits(page);await shot(page,info,'equipos',true);expect(await writes(page)).toEqual([]);
});

for(const viewport of [{width:1440,height:700},{width:390,height:500}]){
 test(`Create user: validation, assignment and safe retry at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page);await page.locator('#accessCreateButton').click();await expect(page.getByLabel('Nombre completo',{exact:true})).toBeFocused();expect(await page.locator('#accessModal').evaluate(n=>n.parentElement===document.body)).toBe(true);
  await modalSave(page).click();expect(await writes(page)).toEqual([]);await page.getByLabel('Nombre completo',{exact:true}).fill('Usuario nuevo de ejemplo');await page.getByLabel('Usuario',{exact:true}).fill('nuevo.ejemplo');await page.getByLabel('Contraseña temporal').fill('fixture-temporary-2026');await page.getByLabel('Rol de acceso').selectOption('role-0');await page.locator('[name="team_ids"][value="team-1"]').check();await hit(page,'#accessField_password');await fits(page);await shot(page,info,'nuevo-usuario');
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await modalSave(page).click();await expect(page.locator('#accessModalMessage')).toContainText('No se pudo crear el usuario');await expect(page.getByLabel('Contraseña temporal')).toHaveValue('fixture-temporary-2026');
  await page.evaluate(()=>{window.__fixtureRejectWrites=false;window.__fixtureWriteDelay=120;});await modalSave(page).evaluate(n=>{n.click();n.click();});await expect(page.locator('#accessModal')).toBeHidden();await expect(page.locator('#accessUsersMetric')).toHaveText('5');
  expect(await writes(page)).toHaveLength(2);expect((await writes(page)).at(-1).body).toEqual({full_name:'Usuario nuevo de ejemplo',username:'nuevo.ejemplo',password:'fixture-temporary-2026',access_role_id:'role-0',team_ids:['team-1']});
 });
 test(`Role composer: templates, all permissions and retained choices at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page);await tab(page,'roles');await page.locator('#accessCreateButton').click();await page.locator('[data-role-template="logistics"]').click();await expect(page.locator('[name="name"]')).toBeFocused();await expect(page.locator('[name="name"]')).toHaveValue('Logística');await expect(page.locator('[name="permission_keys"]')).toHaveCount(29);
  await page.locator('[name="permission_keys"][value="reports.read"]').check();await page.locator('[name="name"]').fill('Logística ampliada');await hit(page,'[name="permission_keys"][value="administration.audit.read"]');await fits(page);await shot(page,info,'nuevo-rol');
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await modalSave(page).click();await expect(page.locator('#accessModalMessage')).toContainText('No se pudo crear el rol');await expect(page.locator('[name="permission_keys"][value="reports.read"]')).toBeChecked();
  await page.evaluate(()=>window.__fixtureRejectWrites=false);await modalSave(page).click();await expect(page.locator('#accessModal')).toBeHidden();const payload=(await writes(page)).at(-1).body;expect(payload.name).toBe('Logística ampliada');expect(payload.permission_keys).toHaveLength(12);expect(payload.permission_keys).toContain('reports.read');expect(payload.permission_keys.some(k=>/^administration\.(users|roles|teams)/.test(k))).toBe(false);
 });
 test(`Teams: active members and safe retry at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page);await tab(page,'teams');await page.locator('#accessCreateButton').click();await expect(page.getByLabel('Nombre',{exact:true})).toBeFocused();await expect(page.locator('[name="member_ids"][value="user-2"]')).toHaveCount(0);
  await page.getByLabel('Nombre',{exact:true}).fill('Equipo de ejemplo');await page.getByLabel('Descripción',{exact:true}).fill('Coordinación de entregas');await page.locator('[name="member_ids"][value="user-1"]').check();await hit(page,'[name="member_ids"][value="user-1"]');await fits(page);await shot(page,info,'nuevo-equipo');
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await modalSave(page).click();await expect(page.locator('#accessModalMessage')).toContainText('No se pudo crear el equipo');await expect(page.locator('[name="member_ids"][value="user-1"]')).toBeChecked();
  await page.evaluate(()=>window.__fixtureRejectWrites=false);await modalSave(page).click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page)).at(-1).body).toEqual({name:'Equipo de ejemplo',description:'Coordinación de entregas',member_ids:['user-1']});
 });
 test(`Account: password validation, recovery and session rotation at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'account');await fits(page);await shot(page,info,'mi-cuenta',true);await expect(page.locator('#accountPermissionMetric')).toHaveText('10');await expect(page.locator('#accountProfile')).toContainText('Ana Pérez');
  await page.locator('#accountPasswordSubmit').click();await expect(page.locator('#accountPasswordStatus')).toContainText('contraseña actual');expect(await writes(page)).toEqual([]);
  await page.getByLabel('Contraseña actual',{exact:true}).fill('fixture-current-2026');await page.getByLabel('Nueva contraseña',{exact:true}).fill('fixture-current-2026');await page.getByLabel('Confirmar contraseña',{exact:true}).fill('fixture-current-2026');await page.locator('#accountPasswordSubmit').click();await expect(page.locator('#accountPasswordStatus')).toContainText('diferente');expect(await writes(page)).toEqual([]);
  await page.getByLabel('Nueva contraseña',{exact:true}).fill('fixture-new-password-2026');await page.getByLabel('Confirmar contraseña',{exact:true}).fill('fixture-new-password-2026');await page.getByRole('button',{name:'Mostrar nueva contraseña',exact:true}).click();await expect(page.locator('#accountNewPassword')).toHaveAttribute('type','text');await expect(page.locator('#accountNewPassword')).toBeFocused();await page.getByRole('button',{name:'Ocultar nueva contraseña',exact:true}).click();await expect(page.locator('#accountNewPassword')).toHaveAttribute('type','password');await expect(page.locator('[data-account-check][data-complete="true"]')).toHaveCount(3);await hit(page,'#accountConfirmPassword');
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await page.locator('#accountPasswordSubmit').click();await expect(page.locator('#accountPasswordStatus')).toContainText('No se pudo actualizar');await expect(page.locator('#accountNewPassword')).toHaveValue('fixture-new-password-2026');
  await page.evaluate(()=>window.__fixtureRejectWrites=false);await page.locator('#accountPasswordSubmit').click();await expect(page.locator('#accountPasswordStatus')).toContainText('Contraseña actualizada');await expect(page.locator('#accountCurrentPassword')).toHaveValue('');await expect(page.locator('#accountNewPassword')).toHaveValue('');expect(await page.evaluate(()=>localStorage.getItem('export_mca_token'))).toBe('fixture-rotated-token');await expect(page.locator('#accountPasswordSubmit')).toBeEnabled();
  expect((await writes(page)).map(c=>c.body)).toEqual(Array(2).fill({current_password:'fixture-current-2026',new_password:'fixture-new-password-2026'}));
 });
 test(`Session revocation: explicit review, focus and retry at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'account');await page.locator('#accountSessionUser').selectOption('actor');await page.locator('#accountSessionReason').fill('x');await page.locator('#accountSessionSubmit').click();await expect(page.locator('#accountSessionStatus')).toContainText('motivo');expect(await writes(page)).toEqual([]);
  await page.locator('#accountSessionReason').fill('Dispositivo de ejemplo perdido');await page.locator('#accountSessionSubmit').click();await expect(page.locator('[data-account-dialog-close]')).toBeFocused();await page.locator('[data-account-dialog-close]').click();await expect(page.locator('#accountSessionSubmit')).toBeFocused();expect(await writes(page)).toEqual([]);
  await page.locator('#accountSessionSubmit').click();await expect(page.locator('#accountConfirmUser')).toContainText('Ana Pérez');await expect(page.locator('#accountConfirmReason')).toContainText('Dispositivo de ejemplo perdido');await fits(page);await shot(page,info,'revocar-sesiones');
  await page.evaluate(()=>window.__fixtureRejectWrites=true);await page.locator('#accountConfirmRevoke').click();await expect(page.locator('#accountConfirmMessage')).toContainText('No se pudieron revocar');await expect(page.locator('#accountConfirmReason')).toContainText('Dispositivo de ejemplo perdido');
  await page.evaluate(()=>window.__fixtureRejectWrites=false);await page.locator('#accountConfirmRevoke').click();await expect(page.locator('#accountConfirmDialog')).toBeHidden();await expect(page.locator('#accountSessionStatus')).toContainText('revocadas correctamente');await expect(page.locator('#accountSessionReason')).toHaveValue('');expect(await page.evaluate(()=>localStorage.getItem('export_mca_token'))).toBe('fixture-revoked-token');expect((await writes(page)).at(-1).body).toEqual({id:'actor',revoke_sessions:true,revoke_reason:'Dispositivo de ejemplo perdido'});
 });
}

test('Access editing: user identity, password reset and focus containment',async({page},info)=>{
 await open(page);const trigger=page.locator('[data-access-action="edit-user"][data-id="user-1"]');await trigger.click();await expect(page.getByLabel('Nombre completo',{exact:true})).toHaveValue('Luis García');await page.getByLabel('Nombre completo',{exact:true}).fill('Luis García Actualizado');await page.getByLabel('Rol de acceso').selectOption('role-0');await page.locator('[name="team_ids"][value="team-0"]').check();await shot(page,info,'editar-usuario');
 await modalSave(page).focus();await page.keyboard.press('Tab');await expect(page.locator('[data-access-close]')).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(modalSave(page)).toBeFocused();await modalSave(page).click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page))[0].body).toEqual({id:'user-1',full_name:'Luis García Actualizado',username:'luis.garcia',access_role_id:'role-0',team_ids:['team-0','team-1']});
 await page.locator('[data-access-action="password-user"][data-id="user-1"]').click();await page.getByLabel('Nueva contraseña',{exact:true}).fill('fixture-reset-password');await shot(page,info,'cambiar-clave-usuario');await modalSave(page).click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page)).at(-1).body).toEqual({id:'user-1',password:'fixture-reset-password'});
});

test('Roles: system permissions stay read-only and custom edits keep identity',async({page},info)=>{
 await open(page);await tab(page,'roles');await page.locator('[data-access-action="edit-role"][data-id="role-system"]').click();await expect(page.locator('#accessEditRoleForm input[type="checkbox"]:disabled')).toHaveCount(29);await expect(modalSave(page)).toHaveCount(0);await expect(page.locator('#accessField_name')).toBeDisabled();await shot(page,info,'permisos-sistema');await closeModal(page);expect(await writes(page)).toEqual([]);
 await page.locator('[data-access-action="edit-role"][data-id="role-0"]').click();await page.locator('#accessField_name').fill('Comercial ampliado');await page.locator('[name="permission_keys"][value="reports.read"]').check();await modalSave(page).click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page))[0].body).toMatchObject({id:'role-0',name:'Comercial ampliado',description:'Ventas y relación con clientes.'});expect((await writes(page))[0].body.permission_keys).toContain('reports.read');
});

test('Access state changes: cancel is safe and teams retain explicit membership warning',async({page},info)=>{
 await open(page);let trigger=page.locator('[data-access-action="toggle-user"][data-id="user-1"]');await trigger.click();await page.locator('#accessModalFoot .access-secondary').click();await expect(trigger).toBeFocused();expect(await writes(page)).toEqual([]);
 await trigger.click();await shot(page,info,'desactivar-usuario');await page.locator('#accessModalFoot .access-danger').click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page))[0].body).toEqual({id:'user-1',is_active:false});
 await tab(page,'teams');await page.locator('[data-access-action="edit-team"][data-id="team-0"]').click();await page.getByLabel('Nombre',{exact:true}).fill('Comercial Norte');await modalSave(page).click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page)).at(-1).body).toEqual({id:'team-0',name:'Comercial Norte',description:'Atención a clientes y ventas.',member_ids:['actor']});
 await page.locator('[data-access-action="toggle-team"][data-id="team-0"]').click();await expect(page.locator('#accessModalBody')).toContainText('membresías quedarán vacías');await page.locator('#accessModalFoot .access-danger').click();await expect(page.locator('#accessModal')).toBeHidden();expect((await writes(page)).at(-1).body).toEqual({id:'team-0',is_active:false});
});

for(const [key,permission]of [['users','administration.users.manage'],['roles','administration.roles.manage'],['teams','administration.teams.manage']])test(`Access permissions expose only the ${key} workspace`,async({page})=>{
 await open(page,'access',{permissions:[permission]});await expect(page.locator('[data-access-tab]')).toHaveCount(1);await expect(page.locator(`[data-access-tab="${key}"]`)).toHaveAttribute('aria-selected','true');expect(await writes(page)).toEqual([]);
});

test('Account without user-management permission hides revocation and avoids its lookup',async({page})=>{
 await open(page,'account',{permissions:['clients.read']});await expect(page.locator('#accountSessionAdminCard')).toBeHidden();await expect(page.locator('#accountPermissionMetric')).toHaveText('1');expect(await page.evaluate(()=>window.__fixtureCalls.some(c=>c.path==='/api/admins'))).toBe(false);expect(await writes(page)).toEqual([]);
});
test('Master account preserves total access and may reset the master password',async({page})=>{
 await open(page,'account',{master:true,permissions:[]});await expect(page.locator('#accountPermissionMetric')).toHaveText('Total');await expect(page.locator('#accountRoleMetric')).toHaveText('Maestro');await expect(page.locator('#accountSessionAdminCard')).toBeVisible();await page.evaluate(()=>window.showSection('adminsSection'));await expect(page.locator('[data-access-action="password-user"][data-id="master"]')).toBeVisible();await expect(page.locator('[data-access-action="edit-user"][data-id="master"],[data-access-action="toggle-user"][data-id="master"]')).toHaveCount(0);expect(await writes(page)).toEqual([]);
});
test('Access read failures retry safely and late tab errors cannot replace the active directory',async({page})=>{
 await open(page,'access',{failRead:true});await expect(page.locator('.access-error')).toBeVisible();await expect(page.locator('#accessWorkspaceMessage')).not.toContainText('Internal fixture');await page.evaluate(()=>window.__fixtureReadError=false);await page.locator('[data-access-action="retry"]').click();await expect(page.locator('.access-card')).toHaveCount(4);
 await page.evaluate(()=>{window.__fixtureReadDelays['/api/access-control?resource=roles']=200;window.__fixtureFailPaths=['/api/access-control?resource=roles'];});await page.locator('[data-access-tab="roles"]').click();await page.locator('[data-access-tab="teams"]').click();await expect(page.locator('#accessTeamsTitle')).toHaveText('Equipos');await expect.poll(()=>page.evaluate(()=>window.__fixtureSettled.includes('/api/access-control?resource=roles'))).toBe(true);await expect(page.locator('#accessTeamsTitle')).toHaveText('Equipos');await expect(page.locator('.access-error')).toHaveCount(0);expect(await writes(page)).toEqual([]);
});
