import {test,expect} from '@playwright/test';
import {homeCommunicationsFixture} from '../../scripts/lib/figma-home-communications-fixture.mjs';
async function open(page,module,options={}){
 const url='https://erp-visual.invalid/',html=homeCommunicationsFixture({module,...options});
 await page.route('**/*',route=>route.request().url()===url?route.fulfill({contentType:'text/html',body:html}):route.abort());
 await page.goto(url);await page.evaluate(()=>document.fonts.ready);
 if(!options.failRead){if(module==='dashboard')await expect(page.locator('.executive-op-card')).toHaveCount(10);else if(module==='alerts')await expect(page.locator('#alertMetricActive')).toHaveText('2');else await expect(page.locator('.notification-item')).toHaveCount(3);}
}
const writes=page=>page.evaluate(()=>window.__fixtureCalls.filter(c=>c.method!=='GET'));
async function shot(page,info,name,fullPage=false){const path=info.outputPath(name+'.png');await page.screenshot({path,fullPage,animations:'disabled',scale:'css'});await info.attach(name,{path,contentType:'image/png'});}
async function fits(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize().width);}
async function hit(page,selector){const node=page.locator(selector);await node.scrollIntoViewIfNeeded();expect(await node.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===el;})).toBe(true);}
async function contrast(page,selector){await page.locator(selector).hover();expect(await page.locator(selector).evaluate(el=>{const s=getComputedStyle(el),l=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),a=l(s.color),b=l(s.backgroundColor);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);})).toBeGreaterThanOrEqual(4.5);}
for(const width of [1440,390]){
 test(`Home: operational summary, separate currencies and disclosed filters at ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:'dark'});await open(page,'dashboard');await fits(page);await expect(page.locator('#dashboardGreeting')).toContainText('Ana');await expect(page.locator('.executive-currency-head h3')).toHaveText(['EUR','USD']);await shot(page,info,'inicio',true);
  const usd=page.locator('.executive-currency-panel').filter({has:page.locator('h3',{hasText:'USD'})}),eur=page.locator('.executive-currency-panel').filter({has:page.locator('h3',{hasText:'EUR'})});
  await usd.locator('summary').click();await expect(usd.locator('.executive-finance-detail')).toHaveJSProperty('open',true);await eur.locator('summary').click();await expect(eur.locator('.executive-finance-detail')).toContainText('No disponible');await expect(eur.locator('.executive-metric.negative strong')).toContainText('600');
  await page.locator('[data-dashboard-detail="filters"] summary').click();await page.locator('#dashboardStartDate').fill('2026-09-01');await page.locator('#dashboardEndDate').fill('2026-09-26');await page.locator('#dashboardCurrency').selectOption('USD');await page.locator('#dashboardClient').selectOption('client-0');await page.locator('#dashboardSupplier').selectOption('supplier-0');await page.locator('#dashboardProduct').selectOption('product-0');await contrast(page,'#dashboardApplyFilters');await page.locator('#dashboardApplyFilters').click();
  await expect(page.locator('.executive-currency-head h3')).toHaveText(['USD']);await expect(page.locator('#dashboardApplyFilters')).toBeFocused();await expect(usd.locator('.executive-finance-detail')).toHaveJSProperty('open',true);await fits(page);await shot(page,info,'inicio-filtros',true);
  const query=await page.evaluate(()=>window.__fixtureCalls.at(-1).query);expect(Object.fromEntries(new URLSearchParams(query))).toEqual({start_date:'2026-09-01',end_date:'2026-09-26',currency:'USD',client_id:'client-0',supplier_id:'supplier-0',product_id:'product-0'});
  await page.locator('#dashboardResetFilters').click();await expect(page.locator('.executive-currency-panel')).toHaveCount(2);await expect(page.locator('#dashboardCurrency')).toHaveValue('');expect(await writes(page)).toEqual([]);
 });
 test(`Alerts: lifecycle filters, search and keyboard views at ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:1000});await open(page,'alerts');await fits(page);await expect(page.locator('.operational-alert-card')).toHaveCount(2);await shot(page,info,'alertas',true);
  await page.locator('#operationalAlertFilter').selectOption('resolved');await expect(page.locator('.operational-alert-card')).toHaveCount(1);await expect(page.locator('[data-alert-action="reopen"]')).toBeVisible();await page.locator('#operationalAlertFilter').selectOption('all');await page.locator('#alertCenterSearch').fill('MCA-DEMO-018');await expect(page.locator('.operational-alert-card')).toHaveCount(1);
  await page.locator('[data-alert-view="operational"]').focus();await page.keyboard.press('End');await expect(page.locator('[data-alert-view="messages"]')).toBeFocused();await expect(page.locator('.alert-message-card')).toHaveCount(2);await expect(page.locator('#notificationsSection')).not.toContainText('PRIVATE_PROVIDER_DIAGNOSTIC');await shot(page,info,'mensajes',true);
  await page.locator('#messageDeliveryFilter').selectOption('issues');await expect(page.locator('.alert-message-card')).toHaveCount(1);await page.locator('#alertCenterSearch').fill('no existe');await expect(page.locator('.alert-center-empty')).toContainText('No hay resultados');expect(await writes(page)).toEqual([]);
 });
 test(`Inbox: reading, hiding, tab keyboard and return focus at ${width}`,async({page},info)=>{
  await page.setViewportSize({width,height:700});await open(page,'inbox');await fits(page);await expect(page.locator('#notificationClose')).toBeFocused();await shot(page,info,'bandeja');
  await page.locator('[data-notification-id="inbox-0"][data-notification-action="mark_read"]').click();await expect(page.locator('.notification-summary-item').first().locator('strong')).toHaveText('1');
  await page.locator('[data-notification-filter="all"]').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('[data-notification-filter="unread"]')).toBeFocused();await expect(page.locator('.notification-item')).toHaveCount(1);await page.keyboard.press('Home');await expect(page.locator('.notification-item')).toHaveCount(3);
  await page.locator('[data-notification-id="inbox-2"][data-notification-action="dismiss"]').click();await expect(page.locator('.notification-item')).toHaveCount(2);await expect(page.locator('[data-notification-view="inbox"]')).toBeFocused();await page.locator('#notificationMarkAllRead').click();await expect(page.locator('#notificationInboxBadge')).toBeHidden();
  await page.keyboard.press('Escape');await expect(page.locator('#notificationInboxOverlay')).toBeHidden();await page.locator('#notificationInboxBell').click();await expect(page.locator('#notificationClose')).toBeFocused();await page.locator('#notificationClose').click();await expect(page.locator('#notificationInboxBell')).toBeFocused();
  expect((await writes(page)).map(c=>c.body.action)).toEqual(['mark_read','dismiss','mark_all_read']);
 });
}
for(const viewport of [{width:1440,height:700},{width:390,height:500}]){
 test(`Alert decisions: reason, snooze, cancellation and scroll at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'alerts');const resolve=page.locator('[data-alert-id="alert-0"][data-alert-action="resolve"]');await resolve.click();await expect(page.locator('#alertActionReason')).toBeFocused();await page.locator('#alertActionReason').fill('');await page.locator('[data-alert-action-confirm]').click();await expect(page.locator('#alertActionError')).toHaveText('Indica un motivo.');expect(await writes(page)).toEqual([]);
  await page.locator('#alertActionReason').fill('Documentos revisados');await contrast(page,'[data-alert-action-confirm]');await expect(page.locator('[data-alert-action-confirm]')).toHaveCSS('background-color','rgb(181, 71, 8)');await expect(page.locator('[data-alert-action-confirm]')).toHaveCSS('box-shadow','none');await hit(page,'[data-alert-action-confirm]');await fits(page);await shot(page,info,'resolver-alerta');await page.keyboard.press('Escape');await expect(resolve).toBeFocused();expect(await writes(page)).toEqual([]);
  await page.locator('[data-alert-id="alert-0"][data-alert-action="snooze"]').click();await expect(page.locator('#alertActionHours')).toBeFocused();await page.locator('#alertActionHours').selectOption('48');await shot(page,info,'posponer-alerta');await page.locator('[data-alert-action-confirm]').click();await expect(page.locator('#operationalAlertFeedback')).toContainText('pospuesta');expect((await writes(page)).at(-1).body).toEqual({id:'alert-0',action:'snooze',hours:48});
  await resolve.click();await page.locator('#alertActionReason').fill('Documentos revisados');await page.locator('[data-alert-action-confirm]').click();await expect(page.locator('#alertMetricActive')).toHaveText('1');await page.locator('#operationalAlertFilter').selectOption('resolved');await expect(page.locator('[data-alert-record="alert-0"]')).toBeVisible();expect((await writes(page)).at(-1).body).toEqual({id:'alert-0',action:'resolve',reason:'Documentos revisados'});
 });
 test(`Message retry requires explicit confirmation and handles failure at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'alerts');await page.locator('[data-alert-view="messages"]').click();await page.locator('[data-message-retry="message-0"]').click();await expect(page.locator('[data-message-retry-cancel]')).toBeFocused();await hit(page,'[data-message-retry-confirm]');await shot(page,info,'reintentar-mensaje');await page.locator('[data-alert-dialog-close]').click();expect(await writes(page)).toEqual([]);
  await page.locator('[data-message-retry="message-0"]').click();await page.evaluate(()=>window.__fixtureRejectWrites=true);await page.locator('[data-message-retry-confirm]').click();await expect(page.locator('#operationalAlertFeedback')).toContainText('No se pudo reintentar');await expect(page.locator('#notificationsSection')).not.toContainText('PRIVATE_FIXTURE_ERROR');
  await page.evaluate(()=>window.__fixtureRejectWrites=false);await page.locator('[data-message-retry="message-0"]').click();await page.locator('[data-message-retry-confirm]').click();await expect(page.locator('[data-message-record="message-0"]')).toContainText('En cola');expect((await writes(page)).map(x=>x.body)).toEqual([{id:'message-0',action:'retry'},{id:'message-0',action:'retry'}]);
 });
 test(`Preferences preserve changes across failed save and refresh at ${viewport.width}`,async({page},info)=>{
  await page.setViewportSize(viewport);await open(page,'inbox');await page.locator('[data-notification-view="preferences"]').click();await expect(page.locator('[data-notification-pref]')).toHaveCount(8);await expect(page.locator('#enablePushDevice')).toBeDisabled();await expect(page.locator('[data-notification-pref="push_enabled"]')).toBeDisabled();
  await page.locator('[data-notification-pref="tracking_updates_enabled"]').uncheck();await page.locator('[data-notification-pref="escalations_enabled"]').uncheck();await page.evaluate(()=>window.__fixtureRejectWrites=true);await page.locator('#saveNotificationPreferences').click();await expect(page.locator('#notificationInboxMessage')).toContainText('No se pudieron guardar');await expect(page.locator('[data-notification-pref="tracking_updates_enabled"]')).not.toBeChecked();
  await page.locator('#notificationRefresh').click();await expect(page.locator('#notificationInboxMessage')).toBeEmpty();await expect(page.locator('[data-notification-pref="tracking_updates_enabled"]')).not.toBeChecked();await contrast(page,'#saveNotificationPreferences');await hit(page,'#saveNotificationPreferences');await fits(page);await shot(page,info,'preferencias');
  await page.locator('#saveNotificationPreferences').focus();await page.keyboard.press('Tab');await expect(page.locator('#notificationMarkAllRead')).toBeFocused();
  await page.evaluate(()=>{window.__fixtureRejectWrites=false;window.__fixtureWriteDelay=100;document.querySelector('#saveNotificationPreferences').click();document.querySelector('#saveNotificationPreferences').click();});await expect(page.locator('#notificationInboxMessage')).toHaveText('Preferencias guardadas.');
  const calls=await writes(page);expect(calls).toHaveLength(2);expect(calls[1].body).toEqual({action:'preferences',in_app_enabled:true,task_assignments_enabled:true,operational_alerts_enabled:true,escalations_enabled:false,tracking_updates_enabled:false,document_updates_enabled:true,integration_failures_enabled:true,push_enabled:false,whatsapp_enabled:false,email_enabled:false});
 });
}
test('Home routes cards and recent activity through canonical navigation',async({page})=>{
 await open(page,'dashboard');for(const target of ['clients','products','suppliers','containers','warehouse','loads','inventory','tasks','alerts'])await page.locator(`.executive-op-card[data-dashboard-open="${target}"]`).first().click();await page.locator('[data-dashboard-shipment="shipment-0"]').click();const routes=await page.evaluate(()=>window.__fixtureNavigation);expect(routes).toContainEqual({module:'Warehouse'});expect(routes).toContainEqual({section:'tasksSection'});expect(routes).toContainEqual({type:'shipment',id:'shipment-0'});expect(await writes(page)).toEqual([]);
});
test('Home retains requested filters when a refresh fails',async({page})=>{
 await open(page,'dashboard');await page.locator('[data-dashboard-detail="filters"] summary').click();await page.locator('#dashboardCurrency').selectOption('EUR');await page.evaluate(()=>window.__fixtureReadError=true);await page.locator('#dashboardApplyFilters').click();await expect(page.locator('#dashboardRetry')).toBeVisible();await expect(page.locator('#dashboardSection')).not.toContainText('PRIVATE_FIXTURE_ERROR');await page.evaluate(()=>window.__fixtureReadError=false);await page.locator('#dashboardRetry').click();await expect(page.locator('.executive-currency-head h3')).toHaveText(['EUR']);await expect(page.locator('#dashboardCurrency')).toHaveValue('EUR');
});
test('Inbox history keeps private diagnostics hidden and retries only the selected memory message',async({page},info)=>{
 await page.setViewportSize({width:1440,height:700});await open(page,'inbox');await page.locator('[data-notification-view="history"]').click();await expect(page.locator('.notification-history-table tbody tr')).toHaveCount(2);await expect(page.locator('.notification-history-table')).not.toContainText('PRIVATE_PROVIDER_DIAGNOSTIC');await shot(page,info,'historial-mensajes');await page.locator('[data-notification-retry="message-0"]').click();await expect(page.locator('.notification-history-status').first()).toHaveText('En cola');expect((await writes(page))[0].body).toEqual({id:'message-0',action:'retry'});
});
test('Inbox opens task context after marking read and recovers a missing destination',async({page})=>{
 await open(page,'inbox');await page.locator('[data-notification-open="inbox-0"]').click();await expect(page.locator('#notificationInboxOverlay')).toBeHidden();expect(await page.evaluate(()=>window.__fixtureNavigation)).toContainEqual({task:'task-0'});await page.locator('#notificationInboxBell').click();await page.evaluate(()=>window.__fixtureMissingDestination=true);await page.locator('[data-notification-open="inbox-1"]').click();await expect(page.locator('#notificationInboxMessage')).toContainText('no tiene un destino');await expect(page.locator('#notificationClose')).toBeFocused();await expect(page.locator('body')).toHaveClass(/notification-inbox-open/);expect((await writes(page)).map(x=>x.body.id)).toEqual(['inbox-0','inbox-1']);
});
test('Read-only notifications hide management while keeping personal reading available',async({page})=>{
 await open(page,'alerts',{writable:false});await expect(page.locator('[data-alert-action="resolve"]').first()).toBeHidden();await expect(page.locator('[data-alert-action="mark_read"]').first()).toBeVisible();await page.locator('[data-alert-view="messages"]').click();await expect(page.locator('[data-message-retry]')).toBeHidden();await open(page,'inbox',{writable:false});await page.locator('[data-notification-view="history"]').click();await expect(page.locator('[data-notification-retry]')).toHaveCount(0);expect(await writes(page)).toEqual([]);
});
test('Restricted dashboard omits unauthorized filter catalogs',async({page})=>{
 await open(page,'dashboard',{restricted:true});await page.locator('[data-dashboard-detail="filters"] summary').click();await expect(page.locator('#dashboardClient,#dashboardSupplier,#dashboardProduct')).toHaveCount(0);expect(await writes(page)).toEqual([]);
});
for(const module of ['dashboard','alerts','inbox'])test(`${module}: failed reads expose safe recovery`,async({page})=>{
 await open(page,module,{failRead:true});const selector=module==='dashboard'?'#dashboardRetry':module==='alerts'?'#reloadUnifiedNotifications':'#notificationRefresh';const message=module==='dashboard'?'.executive-state-error':module==='alerts'?'#operationalAlertFeedback':'#notificationInboxMessage';await expect(page.locator(message)).toContainText(module==='dashboard'?'temporalmente':module==='alerts'?'No se pudieron':'No se pudieron');await expect(page.locator('body')).not.toContainText('PRIVATE_FIXTURE_ERROR');await page.evaluate(()=>window.__fixtureReadError=false);await page.locator(selector).click();if(module==='dashboard')await expect(page.locator('.executive-op-card')).toHaveCount(10);else if(module==='alerts')await expect(page.locator('#alertMetricActive')).toHaveText('2');else await expect(page.locator('.notification-item')).toHaveCount(3);expect(await writes(page)).toEqual([]);
});
